apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dstream
resources:
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - migrate-job.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - secret.yaml
  - server-deployment.yaml
  - server-pdb.yaml
  - server-service.yaml
  - serviceaccount.yaml
  - web-configmap.yaml
  - web-deployment.yaml
  - web-pdb.yaml
  - web-service.yaml
  - worker-deployment.yaml
