{{- if gt (int .Values.server.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dstream.fullname" . }}-server
  labels:
    {{- include "dstream.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "dstream.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
