apiVersion: v1
kind: Service
metadata:
  name: {{ include "dstream.fullname" . }}-server
  labels:
    {{- include "dstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "dstream.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
  - { name: http, port: 8080, targetPort: http }
