{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dstream.serviceAccountName" . }}
  labels:
    {{- include "dstream.labels" . | nindent 4 }}
{{- end }}
