// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllOrganizations = `-- name: ListAllOrganizations :many
SELECT id, name, slug, created_at
FROM organizations ORDER BY created_at DESC LIMIT 200
`

type ListAllOrganizationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Pinned to the four columns the console's org list renders, not `SELECT *`.
// The quota and plan columns live on this table, so a bare star widens this
// row — and anything that serializes it — every time a column is added. The
// same pin was applied to GetOrganizationByID, GetOrganizationBySlug,
// CreateOrganization and UpdateOrgName on 2026-10-02 after exactly that
// happened; this query was the one missed. Widening the list is a deliberate
// API change, so make it one.
func (q *Queries) ListAllOrganizations(ctx context.Context) ([]ListAllOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listAllOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrganizationsRow{}
	for rows.Next() {
		var i ListAllOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
