// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, name, prefix, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, prefix, key_hash, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	Name    string      `json:"name"`
	Prefix  string      `json:"prefix"`
	KeyHash []byte      `json:"key_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrgID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, org_id, name, prefix, key_hash, last_used_at, revoked_at, created_at FROM api_keys
WHERE prefix = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByOrg = `-- name: ListAPIKeysByOrg :many
SELECT id, org_id, name, prefix, key_hash, last_used_at, revoked_at, created_at FROM api_keys
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKeyForOrg = `-- name: RevokeAPIKeyForOrg :exec
UPDATE api_keys
   SET revoked_at = now()
 WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) RevokeAPIKeyForOrg(ctx context.Context, arg RevokeAPIKeyForOrgParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyForOrg, arg.ID, arg.OrgID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
   SET last_used_at = now()
 WHERE id = $1
   AND (last_used_at IS NULL OR last_used_at < now() - INTERVAL '1 minute')
`

func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
