// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpApplicationPortalEpoch = `-- name: BumpApplicationPortalEpoch :exec
UPDATE applications SET portal_epoch = portal_epoch + 1, updated_at = now()
WHERE id = $1 AND org_id = $2
`

type BumpApplicationPortalEpochParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) BumpApplicationPortalEpoch(ctx context.Context, arg BumpApplicationPortalEpochParams) error {
	_, err := q.db.Exec(ctx, bumpApplicationPortalEpoch, arg.ID, arg.OrgID)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (org_id, uid, name, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational
`

type CreateApplicationParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Uid      *string     `json:"uid"`
	Name     string      `json:"name"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.OrgID,
		arg.Uid,
		arg.Name,
		arg.Metadata,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Uid,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalEpoch,
		&i.IsOperational,
	)
	return i, err
}

const deleteApplicationForOrg = `-- name: DeleteApplicationForOrg :one
DELETE FROM applications WHERE id = $1 AND org_id = $2 AND is_operational = FALSE RETURNING id
`

type DeleteApplicationForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteApplicationForOrg(ctx context.Context, arg DeleteApplicationForOrgParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteApplicationForOrg, arg.ID, arg.OrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureOperationalApp = `-- name: EnsureOperationalApp :one
WITH ins AS (
  INSERT INTO applications (org_id, name, is_operational)
  VALUES ($1, 'Operational Webhooks', TRUE)
  ON CONFLICT (org_id) WHERE is_operational DO NOTHING
  RETURNING id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational
)
SELECT id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational FROM ins
UNION ALL
SELECT id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational FROM applications WHERE org_id = $1 AND is_operational
LIMIT 1
`

type EnsureOperationalAppRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Uid           *string            `json:"uid"`
	Name          string             `json:"name"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PortalEpoch   int64              `json:"portal_epoch"`
	IsOperational bool               `json:"is_operational"`
}

// Idempotent create-or-get of the org's operational app (one per org via the
// partial unique index). Returns the existing or newly-created row.
func (q *Queries) EnsureOperationalApp(ctx context.Context, orgID pgtype.UUID) (EnsureOperationalAppRow, error) {
	row := q.db.QueryRow(ctx, ensureOperationalApp, orgID)
	var i EnsureOperationalAppRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Uid,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalEpoch,
		&i.IsOperational,
	)
	return i, err
}

const getApplicationForOrg = `-- name: GetApplicationForOrg :one
SELECT id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational FROM applications WHERE id = $1 AND org_id = $2
`

type GetApplicationForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetApplicationForOrg(ctx context.Context, arg GetApplicationForOrgParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationForOrg, arg.ID, arg.OrgID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Uid,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalEpoch,
		&i.IsOperational,
	)
	return i, err
}

const getOperationalApp = `-- name: GetOperationalApp :one
SELECT id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational FROM applications WHERE org_id = $1 AND is_operational
`

func (q *Queries) GetOperationalApp(ctx context.Context, orgID pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getOperationalApp, orgID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Uid,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalEpoch,
		&i.IsOperational,
	)
	return i, err
}

const listApplicationsByOrg = `-- name: ListApplicationsByOrg :many
SELECT id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational FROM applications
 WHERE org_id = $1
   AND is_operational = FALSE
   AND (created_at, id) < ($2::timestamptz, $3::uuid)
 ORDER BY created_at DESC, id DESC
 LIMIT $4
`

type ListApplicationsByOrgParams struct {
	OrgID    pgtype.UUID        `json:"org_id"`
	CursorTs pgtype.Timestamptz `json:"cursor_ts"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	Lim      int32              `json:"lim"`
}

func (q *Queries) ListApplicationsByOrg(ctx context.Context, arg ListApplicationsByOrgParams) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByOrg,
		arg.OrgID,
		arg.CursorTs,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Uid,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PortalEpoch,
			&i.IsOperational,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
   SET name     = COALESCE($1, name),
       uid      = COALESCE($2, uid),
       metadata = COALESCE($3::jsonb, metadata),
       updated_at = now()
 WHERE id = $4 AND org_id = $5 AND is_operational = FALSE
 RETURNING id, org_id, uid, name, metadata, created_at, updated_at, portal_epoch, is_operational
`

type UpdateApplicationParams struct {
	Name     *string     `json:"name"`
	Uid      *string     `json:"uid"`
	Metadata []byte      `json:"metadata"`
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.Name,
		arg.Uid,
		arg.Metadata,
		arg.ID,
		arg.OrgID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Uid,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PortalEpoch,
		&i.IsOperational,
	)
	return i, err
}
