// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (
    event_id, attempt_num, response_status, response_headers, response_body,
    duration_ms, queued_in_ms, error_message
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_id, attempt_num, response_status, response_headers, response_body, duration_ms, queued_in_ms, error_message, attempted_at
`

type CreateAttemptParams struct {
	EventID         pgtype.UUID `json:"event_id"`
	AttemptNum      int32       `json:"attempt_num"`
	ResponseStatus  *int32      `json:"response_status"`
	ResponseHeaders []byte      `json:"response_headers"`
	ResponseBody    []byte      `json:"response_body"`
	DurationMs      *int32      `json:"duration_ms"`
	QueuedInMs      *int32      `json:"queued_in_ms"`
	ErrorMessage    *string     `json:"error_message"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.EventID,
		arg.AttemptNum,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.DurationMs,
		arg.QueuedInMs,
		arg.ErrorMessage,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.AttemptNum,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.DurationMs,
		&i.QueuedInMs,
		&i.ErrorMessage,
		&i.AttemptedAt,
	)
	return i, err
}

const listAttemptsByEvent = `-- name: ListAttemptsByEvent :many
SELECT id, event_id, attempt_num, response_status, response_headers, response_body, duration_ms, queued_in_ms, error_message, attempted_at FROM attempts
WHERE event_id = $1
ORDER BY attempt_num ASC
`

func (q *Queries) ListAttemptsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.AttemptNum,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.DurationMs,
			&i.QueuedInMs,
			&i.ErrorMessage,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
