// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    org_id, actor_user_id, actor_api_key_id, actor_email_snapshot,
    action, target_type, target_id, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ActorUserID        pgtype.UUID `json:"actor_user_id"`
	ActorApiKeyID      pgtype.UUID `json:"actor_api_key_id"`
	ActorEmailSnapshot *string     `json:"actor_email_snapshot"`
	Action             string      `json:"action"`
	TargetType         string      `json:"target_type"`
	TargetID           pgtype.UUID `json:"target_id"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorUserID,
		arg.ActorApiKeyID,
		arg.ActorEmailSnapshot,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	return err
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT a.id, a.org_id, a.actor_user_id, a.actor_api_key_id, a.actor_email_snapshot, a.action, a.target_type, a.target_id, a.metadata, a.created_at, a.org_name_snapshot,
       COALESCE(u.email::text, '')::text AS actor_user_email_join,
       COALESCE(u.name,        '')::text AS actor_user_name_join,
       COALESCE(k.name,        '')::text AS actor_api_key_name_join
  FROM audit_logs a
  LEFT JOIN users    u ON u.id = a.actor_user_id
  LEFT JOIN api_keys k ON k.id = a.actor_api_key_id
 WHERE a.org_id = $1
   AND ($3::bigint    IS NULL OR a.id           < $3)
   AND ($4::uuid  IS NULL OR a.actor_user_id = $4)
   AND ($5::text    IS NULL OR a.target_type   = $5)
   AND ($6::text         IS NULL OR a.action        = $6)
 ORDER BY a.id DESC
 LIMIT $2
`

type ListAuditLogsByOrgParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Limit       int32       `json:"limit"`
	BeforeID    *int64      `json:"before_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	TargetType  *string     `json:"target_type"`
	Action      *string     `json:"action"`
}

type ListAuditLogsByOrgRow struct {
	ID                  int64              `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	ActorUserID         pgtype.UUID        `json:"actor_user_id"`
	ActorApiKeyID       pgtype.UUID        `json:"actor_api_key_id"`
	ActorEmailSnapshot  *string            `json:"actor_email_snapshot"`
	Action              string             `json:"action"`
	TargetType          string             `json:"target_type"`
	TargetID            pgtype.UUID        `json:"target_id"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	OrgNameSnapshot     *string            `json:"org_name_snapshot"`
	ActorUserEmailJoin  string             `json:"actor_user_email_join"`
	ActorUserNameJoin   string             `json:"actor_user_name_join"`
	ActorApiKeyNameJoin string             `json:"actor_api_key_name_join"`
}

// LEFT JOIN may yield NULL for u/k columns; COALESCE so sqlc generates
// non-nullable string fields (sqlc + LEFT JOIN nullability is awkward).
func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]ListAuditLogsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg,
		arg.OrgID,
		arg.Limit,
		arg.BeforeID,
		arg.ActorUserID,
		arg.TargetType,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByOrgRow{}
	for rows.Next() {
		var i ListAuditLogsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.ActorApiKeyID,
			&i.ActorEmailSnapshot,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.OrgNameSnapshot,
			&i.ActorUserEmailJoin,
			&i.ActorUserNameJoin,
			&i.ActorApiKeyNameJoin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
