// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAutoBookmark = `-- name: CreateAutoBookmark :one
INSERT INTO bookmarks (org_id, request_id, name, description, tags, capture_rule_id)
VALUES ($1, $2, $3, '', '{}', $4) RETURNING id, org_id, request_id, name, description, tags, created_at, capture_rule_id
`

type CreateAutoBookmarkParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	RequestID     pgtype.UUID `json:"request_id"`
	Name          string      `json:"name"`
	CaptureRuleID pgtype.UUID `json:"capture_rule_id"`
}

func (q *Queries) CreateAutoBookmark(ctx context.Context, arg CreateAutoBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createAutoBookmark,
		arg.OrgID,
		arg.RequestID,
		arg.Name,
		arg.CaptureRuleID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.CaptureRuleID,
	)
	return i, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (org_id, request_id, name, description, tags)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, request_id, name, description, tags, created_at, capture_rule_id
`

type CreateBookmarkParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	RequestID   pgtype.UUID `json:"request_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark,
		arg.OrgID,
		arg.RequestID,
		arg.Name,
		arg.Description,
		arg.Tags,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.CaptureRuleID,
	)
	return i, err
}

const deleteBookmarkForOrg = `-- name: DeleteBookmarkForOrg :execrows
DELETE FROM bookmarks WHERE id = $1 AND org_id = $2
`

type DeleteBookmarkForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteBookmarkForOrg(ctx context.Context, arg DeleteBookmarkForOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookmarkForOrg, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const evictCaptureBookmarks = `-- name: EvictCaptureBookmarks :exec
DELETE FROM bookmarks b
WHERE b.capture_rule_id = $1
  AND b.id NOT IN (
    SELECT id FROM bookmarks WHERE capture_rule_id = $1 ORDER BY created_at DESC LIMIT $2
  )
`

type EvictCaptureBookmarksParams struct {
	CaptureRuleID pgtype.UUID `json:"capture_rule_id"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) EvictCaptureBookmarks(ctx context.Context, arg EvictCaptureBookmarksParams) error {
	_, err := q.db.Exec(ctx, evictCaptureBookmarks, arg.CaptureRuleID, arg.Limit)
	return err
}

const getBookmarkForOrg = `-- name: GetBookmarkForOrg :one
SELECT id, org_id, request_id, name, description, tags, created_at, capture_rule_id FROM bookmarks WHERE id = $1 AND org_id = $2
`

type GetBookmarkForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetBookmarkForOrg(ctx context.Context, arg GetBookmarkForOrgParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, getBookmarkForOrg, arg.ID, arg.OrgID)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.CaptureRuleID,
	)
	return i, err
}

const listBookmarksForOrg = `-- name: ListBookmarksForOrg :many
SELECT b.id, b.org_id, b.request_id, b.name, b.description, b.tags, b.created_at, b.capture_rule_id, r.source_id, r.http_method, r.http_path, r.received_at AS captured_at
FROM bookmarks b
JOIN requests r ON r.id = b.request_id
WHERE b.org_id = $1
  AND ($2::uuid IS NULL OR r.source_id = $2)
  AND ($3::text IS NULL OR $3 = ANY(b.tags))
ORDER BY b.created_at DESC
`

type ListBookmarksForOrgParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	SourceID pgtype.UUID `json:"source_id"`
	Tag      *string     `json:"tag"`
}

type ListBookmarksForOrgRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	RequestID     pgtype.UUID        `json:"request_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Tags          []string           `json:"tags"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CaptureRuleID pgtype.UUID        `json:"capture_rule_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	HTTPMethod    string             `json:"http_method"`
	HTTPPath      string             `json:"http_path"`
	CapturedAt    pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) ListBookmarksForOrg(ctx context.Context, arg ListBookmarksForOrgParams) ([]ListBookmarksForOrgRow, error) {
	rows, err := q.db.Query(ctx, listBookmarksForOrg, arg.OrgID, arg.SourceID, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksForOrgRow{}
	for rows.Next() {
		var i ListBookmarksForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.CaptureRuleID,
			&i.SourceID,
			&i.HTTPMethod,
			&i.HTTPPath,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
