// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_rules.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureRule = `-- name: CreateCaptureRule :one
INSERT INTO capture_rules (org_id, source_id, name, filter_expr, cap, enabled)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, org_id, source_id, name, filter_expr, cap, enabled, created_at, updated_at
`

type CreateCaptureRuleParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	SourceID   pgtype.UUID `json:"source_id"`
	Name       string      `json:"name"`
	FilterExpr *string     `json:"filter_expr"`
	Cap        int32       `json:"cap"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) CreateCaptureRule(ctx context.Context, arg CreateCaptureRuleParams) (CaptureRule, error) {
	row := q.db.QueryRow(ctx, createCaptureRule,
		arg.OrgID,
		arg.SourceID,
		arg.Name,
		arg.FilterExpr,
		arg.Cap,
		arg.Enabled,
	)
	var i CaptureRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.Name,
		&i.FilterExpr,
		&i.Cap,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCaptureRuleForOrg = `-- name: DeleteCaptureRuleForOrg :execrows
DELETE FROM capture_rules WHERE id = $1 AND org_id = $2
`

type DeleteCaptureRuleForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteCaptureRuleForOrg(ctx context.Context, arg DeleteCaptureRuleForOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCaptureRuleForOrg, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaptureRuleForOrg = `-- name: GetCaptureRuleForOrg :one
SELECT id, org_id, source_id, name, filter_expr, cap, enabled, created_at, updated_at FROM capture_rules WHERE id = $1 AND org_id = $2
`

type GetCaptureRuleForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetCaptureRuleForOrg(ctx context.Context, arg GetCaptureRuleForOrgParams) (CaptureRule, error) {
	row := q.db.QueryRow(ctx, getCaptureRuleForOrg, arg.ID, arg.OrgID)
	var i CaptureRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.Name,
		&i.FilterExpr,
		&i.Cap,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCaptureRulesForOrg = `-- name: ListCaptureRulesForOrg :many
SELECT id, org_id, source_id, name, filter_expr, cap, enabled, created_at, updated_at FROM capture_rules
WHERE org_id = $1 AND ($2::uuid IS NULL OR source_id = $2)
ORDER BY created_at DESC
`

type ListCaptureRulesForOrgParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	SourceID pgtype.UUID `json:"source_id"`
}

func (q *Queries) ListCaptureRulesForOrg(ctx context.Context, arg ListCaptureRulesForOrgParams) ([]CaptureRule, error) {
	rows, err := q.db.Query(ctx, listCaptureRulesForOrg, arg.OrgID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaptureRule{}
	for rows.Next() {
		var i CaptureRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SourceID,
			&i.Name,
			&i.FilterExpr,
			&i.Cap,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCaptureRulesBySource = `-- name: ListEnabledCaptureRulesBySource :many
SELECT id, name, cap, filter_expr FROM capture_rules
WHERE source_id = $1 AND enabled = TRUE
`

type ListEnabledCaptureRulesBySourceRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Cap        int32       `json:"cap"`
	FilterExpr *string     `json:"filter_expr"`
}

func (q *Queries) ListEnabledCaptureRulesBySource(ctx context.Context, sourceID pgtype.UUID) ([]ListEnabledCaptureRulesBySourceRow, error) {
	rows, err := q.db.Query(ctx, listEnabledCaptureRulesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledCaptureRulesBySourceRow{}
	for rows.Next() {
		var i ListEnabledCaptureRulesBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cap,
			&i.FilterExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaptureRule = `-- name: UpdateCaptureRule :one
UPDATE capture_rules
SET name = $3, filter_expr = $4, cap = $5, enabled = $6, updated_at = now()
WHERE id = $1 AND org_id = $2 RETURNING id, org_id, source_id, name, filter_expr, cap, enabled, created_at, updated_at
`

type UpdateCaptureRuleParams struct {
	ID         pgtype.UUID `json:"id"`
	OrgID      pgtype.UUID `json:"org_id"`
	Name       string      `json:"name"`
	FilterExpr *string     `json:"filter_expr"`
	Cap        int32       `json:"cap"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) UpdateCaptureRule(ctx context.Context, arg UpdateCaptureRuleParams) (CaptureRule, error) {
	row := q.db.QueryRow(ctx, updateCaptureRule,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.FilterExpr,
		arg.Cap,
		arg.Enabled,
	)
	var i CaptureRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SourceID,
		&i.Name,
		&i.FilterExpr,
		&i.Cap,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
