// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (source_id, destination_id, enabled)
VALUES ($1, $2, $3)
RETURNING id, source_id, destination_id, enabled, max_retries, retry_strategy, retry_base_ms, retry_cap_ms, retry_jitter_pct, custom_retry_schedule, created_at, updated_at
`

type CreateConnectionParams struct {
	SourceID      pgtype.UUID `json:"source_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
	Enabled       bool        `json:"enabled"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection, arg.SourceID, arg.DestinationID, arg.Enabled)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const deleteConnectionForOrg = `-- name: DeleteConnectionForOrg :exec
DELETE FROM connections AS c
 WHERE c.id = $1
   AND c.source_id IN (SELECT s.id FROM sources s WHERE s.org_id = $2)
`

type DeleteConnectionForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteConnectionForOrg(ctx context.Context, arg DeleteConnectionForOrgParams) error {
	_, err := q.db.Exec(ctx, deleteConnectionForOrg, arg.ID, arg.OrgID)
	return err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, source_id, destination_id, enabled, max_retries, retry_strategy, retry_base_ms, retry_cap_ms, retry_jitter_pct, custom_retry_schedule, created_at, updated_at FROM connections WHERE id = $1
`

func (q *Queries) GetConnectionByID(ctx context.Context, id pgtype.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionForOrg = `-- name: GetConnectionForOrg :one
SELECT c.id, c.source_id, c.destination_id, c.enabled, c.max_retries, c.retry_strategy, c.retry_base_ms, c.retry_cap_ms, c.retry_jitter_pct, c.custom_retry_schedule, c.created_at, c.updated_at
  FROM connections c
  JOIN sources s ON s.id = c.source_id
 WHERE c.id = $1
   AND s.org_id = $2
`

type GetConnectionForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetConnectionForOrg(ctx context.Context, arg GetConnectionForOrgParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionForOrg, arg.ID, arg.OrgID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsByOrg = `-- name: ListConnectionsByOrg :many
SELECT c.id, c.source_id, c.destination_id, c.enabled, c.max_retries, c.retry_strategy, c.retry_base_ms, c.retry_cap_ms, c.retry_jitter_pct, c.custom_retry_schedule, c.created_at, c.updated_at
  FROM connections c
  JOIN sources s ON s.id = c.source_id
 WHERE s.org_id = $1
 ORDER BY c.created_at DESC
`

func (q *Queries) ListConnectionsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.Enabled,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.RetryBaseMs,
			&i.RetryCapMs,
			&i.RetryJitterPct,
			&i.CustomRetrySchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsBySource = `-- name: ListConnectionsBySource :many
SELECT id, source_id, destination_id, enabled, max_retries, retry_strategy, retry_base_ms, retry_cap_ms, retry_jitter_pct, custom_retry_schedule, created_at, updated_at FROM connections
WHERE source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConnectionsBySource(ctx context.Context, sourceID pgtype.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.Enabled,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.RetryBaseMs,
			&i.RetryCapMs,
			&i.RetryJitterPct,
			&i.CustomRetrySchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledConnectionsBySource = `-- name: ListEnabledConnectionsBySource :many
SELECT id, source_id, destination_id, enabled, max_retries, retry_strategy, retry_base_ms, retry_cap_ms, retry_jitter_pct, custom_retry_schedule, created_at, updated_at FROM connections
WHERE source_id = $1 AND enabled = TRUE
`

func (q *Queries) ListEnabledConnectionsBySource(ctx context.Context, sourceID pgtype.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listEnabledConnectionsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.DestinationID,
			&i.Enabled,
			&i.MaxRetries,
			&i.RetryStrategy,
			&i.RetryBaseMs,
			&i.RetryCapMs,
			&i.RetryJitterPct,
			&i.CustomRetrySchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchConnectionForOrg = `-- name: PatchConnectionForOrg :one
UPDATE connections AS c
   SET enabled               = COALESCE($1,               c.enabled),
       max_retries           = COALESCE($2,           c.max_retries),
       retry_strategy        = COALESCE($3,        c.retry_strategy),
       retry_base_ms         = COALESCE($4,         c.retry_base_ms),
       retry_cap_ms          = COALESCE($5,          c.retry_cap_ms),
       retry_jitter_pct      = COALESCE($6,      c.retry_jitter_pct),
       custom_retry_schedule = COALESCE($7, c.custom_retry_schedule),
       updated_at            = now()
  FROM sources s
 WHERE c.id = $8
   AND c.source_id = s.id
   AND s.org_id = $9
 RETURNING c.id, c.source_id, c.destination_id, c.enabled, c.max_retries, c.retry_strategy, c.retry_base_ms, c.retry_cap_ms, c.retry_jitter_pct, c.custom_retry_schedule, c.created_at, c.updated_at
`

type PatchConnectionForOrgParams struct {
	Enabled             *bool       `json:"enabled"`
	MaxRetries          *int32      `json:"max_retries"`
	RetryStrategy       *string     `json:"retry_strategy"`
	RetryBaseMs         *int32      `json:"retry_base_ms"`
	RetryCapMs          *int32      `json:"retry_cap_ms"`
	RetryJitterPct      *int32      `json:"retry_jitter_pct"`
	CustomRetrySchedule []byte      `json:"custom_retry_schedule"`
	ID                  pgtype.UUID `json:"id"`
	OrgID               pgtype.UUID `json:"org_id"`
}

// COALESCE pattern so unspecified fields keep current values.
// Tenancy is enforced by joining through sources.org_id.
func (q *Queries) PatchConnectionForOrg(ctx context.Context, arg PatchConnectionForOrgParams) (Connection, error) {
	row := q.db.QueryRow(ctx, patchConnectionForOrg,
		arg.Enabled,
		arg.MaxRetries,
		arg.RetryStrategy,
		arg.RetryBaseMs,
		arg.RetryCapMs,
		arg.RetryJitterPct,
		arg.CustomRetrySchedule,
		arg.ID,
		arg.OrgID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE connections
SET enabled               = COALESCE($1,               enabled),
    max_retries           = COALESCE($2,           max_retries),
    retry_strategy        = COALESCE($3,        retry_strategy),
    retry_base_ms         = COALESCE($4,         retry_base_ms),
    retry_cap_ms          = COALESCE($5,          retry_cap_ms),
    retry_jitter_pct      = COALESCE($6,      retry_jitter_pct),
    custom_retry_schedule = COALESCE($7, custom_retry_schedule),
    updated_at            = now()
WHERE id = $8
RETURNING id, source_id, destination_id, enabled, max_retries, retry_strategy, retry_base_ms, retry_cap_ms, retry_jitter_pct, custom_retry_schedule, created_at, updated_at
`

type UpdateConnectionParams struct {
	Enabled             *bool       `json:"enabled"`
	MaxRetries          *int32      `json:"max_retries"`
	RetryStrategy       *string     `json:"retry_strategy"`
	RetryBaseMs         *int32      `json:"retry_base_ms"`
	RetryCapMs          *int32      `json:"retry_cap_ms"`
	RetryJitterPct      *int32      `json:"retry_jitter_pct"`
	CustomRetrySchedule []byte      `json:"custom_retry_schedule"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnection,
		arg.Enabled,
		arg.MaxRetries,
		arg.RetryStrategy,
		arg.RetryBaseMs,
		arg.RetryCapMs,
		arg.RetryJitterPct,
		arg.CustomRetrySchedule,
		arg.ID,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.DestinationID,
		&i.Enabled,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
