// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (org_id, name, type, description, url, auth_config,
                           rate_limit_rps, rate_limit_burst, max_inflight)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at, description
`

type CreateDestinationParams struct {
	OrgID          pgtype.UUID `json:"org_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	Description    string      `json:"description"`
	Url            *string     `json:"url"`
	AuthConfig     []byte      `json:"auth_config"`
	RateLimitRps   *int32      `json:"rate_limit_rps"`
	RateLimitBurst *int32      `json:"rate_limit_burst"`
	MaxInflight    *int32      `json:"max_inflight"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Url,
		arg.AuthConfig,
		arg.RateLimitRps,
		arg.RateLimitBurst,
		arg.MaxInflight,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const deleteDestinationForOrg = `-- name: DeleteDestinationForOrg :exec
DELETE FROM destinations WHERE id = $1 AND org_id = $2
`

type DeleteDestinationForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteDestinationForOrg(ctx context.Context, arg DeleteDestinationForOrgParams) error {
	_, err := q.db.Exec(ctx, deleteDestinationForOrg, arg.ID, arg.OrgID)
	return err
}

const getDestinationForOrg = `-- name: GetDestinationForOrg :one
SELECT id, org_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at, description FROM destinations WHERE id = $1 AND org_id = $2
`

type GetDestinationForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetDestinationForOrg(ctx context.Context, arg GetDestinationForOrgParams) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestinationForOrg, arg.ID, arg.OrgID)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}

const listDestinationsByOrg = `-- name: ListDestinationsByOrg :many
SELECT id, org_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at, description FROM destinations
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDestinationsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Destination, error) {
	rows, err := q.db.Query(ctx, listDestinationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.AuthConfig,
			&i.RateLimitRps,
			&i.RateLimitBurst,
			&i.MaxInflight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchDestinationForOrg = `-- name: PatchDestinationForOrg :one
UPDATE destinations
   SET name             = COALESCE($3,             name),
       type             = COALESCE($4,             type),
       description      = COALESCE($5,      description),
       url              = COALESCE($6,              url),
       auth_config      = COALESCE($7,      auth_config),
       rate_limit_rps   = COALESCE($8,   rate_limit_rps),
       rate_limit_burst = COALESCE($9, rate_limit_burst),
       max_inflight     = COALESCE($10,     max_inflight),
       updated_at       = now()
 WHERE id = $1 AND org_id = $2
 RETURNING id, org_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at, description
`

type PatchDestinationForOrgParams struct {
	ID             pgtype.UUID `json:"id"`
	OrgID          pgtype.UUID `json:"org_id"`
	Name           *string     `json:"name"`
	Type           *string     `json:"type"`
	Description    *string     `json:"description"`
	Url            *string     `json:"url"`
	AuthConfig     []byte      `json:"auth_config"`
	RateLimitRps   *int32      `json:"rate_limit_rps"`
	RateLimitBurst *int32      `json:"rate_limit_burst"`
	MaxInflight    *int32      `json:"max_inflight"`
}

// COALESCE pattern so unspecified fields keep current values.
func (q *Queries) PatchDestinationForOrg(ctx context.Context, arg PatchDestinationForOrgParams) (Destination, error) {
	row := q.db.QueryRow(ctx, patchDestinationForOrg,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Url,
		arg.AuthConfig,
		arg.RateLimitRps,
		arg.RateLimitBurst,
		arg.MaxInflight,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
	)
	return i, err
}
