// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (
    project_id, name, type, url, auth_config,
    rate_limit_rps, rate_limit_burst, max_inflight
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at
`

type CreateDestinationParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	Url            *string     `json:"url"`
	AuthConfig     []byte      `json:"auth_config"`
	RateLimitRps   *int32      `json:"rate_limit_rps"`
	RateLimitBurst *int32      `json:"rate_limit_burst"`
	MaxInflight    *int32      `json:"max_inflight"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.AuthConfig,
		arg.RateLimitRps,
		arg.RateLimitBurst,
		arg.MaxInflight,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = $1
`

func (q *Queries) DeleteDestination(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDestination, id)
	return err
}

const getDestinationByID = `-- name: GetDestinationByID :one
SELECT id, project_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at FROM destinations WHERE id = $1
`

func (q *Queries) GetDestinationByID(ctx context.Context, id pgtype.UUID) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestinationByID, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinationsByProject = `-- name: ListDestinationsByProject :many
SELECT id, project_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at FROM destinations
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDestinationsByProject(ctx context.Context, projectID pgtype.UUID) ([]Destination, error) {
	rows, err := q.db.Query(ctx, listDestinationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Destination{}
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.AuthConfig,
			&i.RateLimitRps,
			&i.RateLimitBurst,
			&i.MaxInflight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE destinations
SET name             = COALESCE($1,             name),
    url              = COALESCE($2,              url),
    auth_config      = COALESCE($3,      auth_config),
    rate_limit_rps   = COALESCE($4,   rate_limit_rps),
    rate_limit_burst = COALESCE($5, rate_limit_burst),
    max_inflight     = COALESCE($6,     max_inflight),
    updated_at       = now()
WHERE id = $7
RETURNING id, project_id, name, type, url, auth_config, rate_limit_rps, rate_limit_burst, max_inflight, created_at, updated_at
`

type UpdateDestinationParams struct {
	Name           *string     `json:"name"`
	Url            *string     `json:"url"`
	AuthConfig     []byte      `json:"auth_config"`
	RateLimitRps   *int32      `json:"rate_limit_rps"`
	RateLimitBurst *int32      `json:"rate_limit_burst"`
	MaxInflight    *int32      `json:"max_inflight"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, updateDestination,
		arg.Name,
		arg.Url,
		arg.AuthConfig,
		arg.RateLimitRps,
		arg.RateLimitBurst,
		arg.MaxInflight,
		arg.ID,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.AuthConfig,
		&i.RateLimitRps,
		&i.RateLimitBurst,
		&i.MaxInflight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
