// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (app_id, org_id, uid, url, description, secret, filter_event_types)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at
`

type CreateEndpointParams struct {
	AppID            pgtype.UUID `json:"app_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	Uid              *string     `json:"uid"`
	Url              string      `json:"url"`
	Description      string      `json:"description"`
	Secret           string      `json:"secret"`
	FilterEventTypes []string    `json:"filter_event_types"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.AppID,
		arg.OrgID,
		arg.Uid,
		arg.Url,
		arg.Description,
		arg.Secret,
		arg.FilterEventTypes,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpointForApp = `-- name: DeleteEndpointForApp :one
DELETE FROM endpoints WHERE id = $1 AND app_id = $2 RETURNING id
`

type DeleteEndpointForAppParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) DeleteEndpointForApp(ctx context.Context, arg DeleteEndpointForAppParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEndpointForApp, arg.ID, arg.AppID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEndpointForApp = `-- name: GetEndpointForApp :one
SELECT id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at FROM endpoints WHERE id = $1 AND app_id = $2
`

type GetEndpointForAppParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetEndpointForApp(ctx context.Context, arg GetEndpointForAppParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointForApp, arg.ID, arg.AppID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointSecret = `-- name: GetEndpointSecret :one
SELECT secret FROM endpoints WHERE id = $1 AND app_id = $2
`

type GetEndpointSecretParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetEndpointSecret(ctx context.Context, arg GetEndpointSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, getEndpointSecret, arg.ID, arg.AppID)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const listEndpointsByApp = `-- name: ListEndpointsByApp :many
SELECT id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at FROM endpoints WHERE app_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListEndpointsByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListEndpointsByApp(ctx context.Context, arg ListEndpointsByAppParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByApp, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.OrgID,
			&i.Uid,
			&i.Url,
			&i.Description,
			&i.Secret,
			&i.FilterEventTypes,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingEndpoints = `-- name: ListMatchingEndpoints :many
SELECT id FROM endpoints
 WHERE app_id = $1
   AND disabled = FALSE
   AND (filter_event_types IS NULL
        OR cardinality(filter_event_types) = 0
        OR $2::text = ANY(filter_event_types))
`

type ListMatchingEndpointsParams struct {
	AppID     pgtype.UUID `json:"app_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) ListMatchingEndpoints(ctx context.Context, arg ListMatchingEndpointsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMatchingEndpoints, arg.AppID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
   SET url         = COALESCE($1, url),
       description = COALESCE($2, description),
       disabled    = COALESCE($3, disabled),
       filter_event_types = CASE WHEN $4::bool
                                 THEN $5::text[]
                                 ELSE filter_event_types END,
       updated_at  = now()
 WHERE id = $6 AND app_id = $7
 RETURNING id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at
`

type UpdateEndpointParams struct {
	Url              *string     `json:"url"`
	Description      *string     `json:"description"`
	Disabled         *bool       `json:"disabled"`
	SetFilter        bool        `json:"set_filter"`
	FilterEventTypes []string    `json:"filter_event_types"`
	ID               pgtype.UUID `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Url,
		arg.Description,
		arg.Disabled,
		arg.SetFilter,
		arg.FilterEventTypes,
		arg.ID,
		arg.AppID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
