// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (app_id, org_id, uid, url, description, secret, filter_event_types, headers, rate_limit, channels)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at, prev_secret, prev_secret_expires_at, consecutive_failures, disabled_at, headers, rate_limit, channels
`

type CreateEndpointParams struct {
	AppID            pgtype.UUID `json:"app_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	Uid              *string     `json:"uid"`
	Url              string      `json:"url"`
	Description      string      `json:"description"`
	Secret           string      `json:"secret"`
	FilterEventTypes []string    `json:"filter_event_types"`
	Headers          []byte      `json:"headers"`
	RateLimit        *int32      `json:"rate_limit"`
	Channels         []string    `json:"channels"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.AppID,
		arg.OrgID,
		arg.Uid,
		arg.Url,
		arg.Description,
		arg.Secret,
		arg.FilterEventTypes,
		arg.Headers,
		arg.RateLimit,
		arg.Channels,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrevSecret,
		&i.PrevSecretExpiresAt,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.Headers,
		&i.RateLimit,
		&i.Channels,
	)
	return i, err
}

const deleteEndpointForApp = `-- name: DeleteEndpointForApp :one
DELETE FROM endpoints WHERE id = $1 AND app_id = $2 RETURNING id
`

type DeleteEndpointForAppParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) DeleteEndpointForApp(ctx context.Context, arg DeleteEndpointForAppParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEndpointForApp, arg.ID, arg.AppID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEndpointForApp = `-- name: GetEndpointForApp :one
SELECT id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at, prev_secret, prev_secret_expires_at, consecutive_failures, disabled_at, headers, rate_limit, channels FROM endpoints WHERE id = $1 AND app_id = $2
`

type GetEndpointForAppParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetEndpointForApp(ctx context.Context, arg GetEndpointForAppParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointForApp, arg.ID, arg.AppID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrevSecret,
		&i.PrevSecretExpiresAt,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.Headers,
		&i.RateLimit,
		&i.Channels,
	)
	return i, err
}

const getEndpointSecret = `-- name: GetEndpointSecret :one
SELECT secret FROM endpoints WHERE id = $1 AND app_id = $2
`

type GetEndpointSecretParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetEndpointSecret(ctx context.Context, arg GetEndpointSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, getEndpointSecret, arg.ID, arg.AppID)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const incrEndpointFailures = `-- name: IncrEndpointFailures :one
WITH prev AS (SELECT ep.id, ep.disabled AS was_disabled FROM endpoints ep WHERE ep.id = $2)
UPDATE endpoints e
   SET consecutive_failures = e.consecutive_failures + 1,
       disabled    = (e.consecutive_failures + 1 >= $1::int) OR e.disabled,
       disabled_at = CASE WHEN (e.consecutive_failures + 1 >= $1::int) AND NOT e.disabled
                          THEN now() ELSE e.disabled_at END,
       updated_at  = now()
  FROM prev
 WHERE e.id = prev.id
 RETURNING e.id, e.org_id, e.app_id, e.url, e.consecutive_failures, e.disabled_at,
           (NOT prev.was_disabled AND e.disabled) AS just_disabled
`

type IncrEndpointFailuresParams struct {
	Threshold int32       `json:"threshold"`
	ID        pgtype.UUID `json:"id"`
}

type IncrEndpointFailuresRow struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	AppID               pgtype.UUID        `json:"app_id"`
	Url                 string             `json:"url"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	DisabledAt          pgtype.Timestamptz `json:"disabled_at"`
	JustDisabled        *bool              `json:"just_disabled"`
}

func (q *Queries) IncrEndpointFailures(ctx context.Context, arg IncrEndpointFailuresParams) (IncrEndpointFailuresRow, error) {
	row := q.db.QueryRow(ctx, incrEndpointFailures, arg.Threshold, arg.ID)
	var i IncrEndpointFailuresRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Url,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.JustDisabled,
	)
	return i, err
}

const listEndpointsByApp = `-- name: ListEndpointsByApp :many
SELECT id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at, prev_secret, prev_secret_expires_at, consecutive_failures, disabled_at, headers, rate_limit, channels FROM endpoints WHERE app_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListEndpointsByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListEndpointsByApp(ctx context.Context, arg ListEndpointsByAppParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsByApp, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.OrgID,
			&i.Uid,
			&i.Url,
			&i.Description,
			&i.Secret,
			&i.FilterEventTypes,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrevSecret,
			&i.PrevSecretExpiresAt,
			&i.ConsecutiveFailures,
			&i.DisabledAt,
			&i.Headers,
			&i.RateLimit,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingEndpoints = `-- name: ListMatchingEndpoints :many
SELECT id FROM endpoints
 WHERE app_id = $1
   AND disabled = FALSE
   AND (filter_event_types IS NULL
        OR cardinality(filter_event_types) = 0
        OR $2::text = ANY(filter_event_types))
   AND (channels IS NULL
        OR cardinality(channels) = 0
        OR channels && $3::text[])
`

type ListMatchingEndpointsParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	EventType   string      `json:"event_type"`
	MsgChannels []string    `json:"msg_channels"`
}

func (q *Queries) ListMatchingEndpoints(ctx context.Context, arg ListMatchingEndpointsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMatchingEndpoints, arg.AppID, arg.EventType, arg.MsgChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetEndpointFailures = `-- name: ResetEndpointFailures :exec
UPDATE endpoints SET consecutive_failures = 0, updated_at = now()
 WHERE id = $1 AND consecutive_failures > 0
`

func (q *Queries) ResetEndpointFailures(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetEndpointFailures, id)
	return err
}

const rotateEndpointSecret = `-- name: RotateEndpointSecret :one
UPDATE endpoints
   SET prev_secret            = secret,
       prev_secret_expires_at = $1,
       secret                 = $2,
       updated_at             = now()
 WHERE id = $3 AND app_id = $4
 RETURNING id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at, prev_secret, prev_secret_expires_at, consecutive_failures, disabled_at, headers, rate_limit, channels
`

type RotateEndpointSecretParams struct {
	PrevExpiresAt pgtype.Timestamptz `json:"prev_expires_at"`
	NewSecret     string             `json:"new_secret"`
	ID            pgtype.UUID        `json:"id"`
	AppID         pgtype.UUID        `json:"app_id"`
}

func (q *Queries) RotateEndpointSecret(ctx context.Context, arg RotateEndpointSecretParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, rotateEndpointSecret,
		arg.PrevExpiresAt,
		arg.NewSecret,
		arg.ID,
		arg.AppID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrevSecret,
		&i.PrevSecretExpiresAt,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.Headers,
		&i.RateLimit,
		&i.Channels,
	)
	return i, err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
   SET url         = COALESCE($1, url),
       description = COALESCE($2, description),
       disabled    = COALESCE($3, disabled),
       consecutive_failures = CASE WHEN $3 = FALSE THEN 0 ELSE consecutive_failures END,
       disabled_at          = CASE WHEN $3 = FALSE THEN NULL ELSE disabled_at END,
       filter_event_types = CASE WHEN $4::bool
                                 THEN $5::text[]
                                 ELSE filter_event_types END,
       headers    = CASE WHEN $6::bool
                         THEN $7::jsonb ELSE headers END,
       rate_limit = COALESCE($8, rate_limit),
       channels   = CASE WHEN $9::bool
                         THEN $10::text[] ELSE channels END,
       updated_at  = now()
 WHERE id = $11 AND app_id = $12
 RETURNING id, app_id, org_id, uid, url, description, secret, filter_event_types, disabled, created_at, updated_at, prev_secret, prev_secret_expires_at, consecutive_failures, disabled_at, headers, rate_limit, channels
`

type UpdateEndpointParams struct {
	Url              *string     `json:"url"`
	Description      *string     `json:"description"`
	Disabled         *bool       `json:"disabled"`
	SetFilter        bool        `json:"set_filter"`
	FilterEventTypes []string    `json:"filter_event_types"`
	SetHeaders       bool        `json:"set_headers"`
	Headers          []byte      `json:"headers"`
	RateLimit        *int32      `json:"rate_limit"`
	SetChannels      bool        `json:"set_channels"`
	Channels         []string    `json:"channels"`
	ID               pgtype.UUID `json:"id"`
	AppID            pgtype.UUID `json:"app_id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Url,
		arg.Description,
		arg.Disabled,
		arg.SetFilter,
		arg.FilterEventTypes,
		arg.SetHeaders,
		arg.Headers,
		arg.RateLimit,
		arg.SetChannels,
		arg.Channels,
		arg.ID,
		arg.AppID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.Uid,
		&i.Url,
		&i.Description,
		&i.Secret,
		&i.FilterEventTypes,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrevSecret,
		&i.PrevSecretExpiresAt,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.Headers,
		&i.RateLimit,
		&i.Channels,
	)
	return i, err
}
