// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimStuckEvents = `-- name: ClaimStuckEvents :many
UPDATE events
   SET status = 'queued', next_retry_at = now(), updated_at = now()
 WHERE id IN (
   SELECT e.id
     FROM events e
     JOIN connections c  ON c.id = e.connection_id
     JOIN destinations d ON d.id = c.destination_id
    WHERE e.updated_at < $1
      AND (
        e.status = 'queued'
        OR (e.status = 'in_flight' AND d.type = 'cli')
      )
    ORDER BY e.updated_at ASC
    LIMIT $2
    FOR UPDATE OF e SKIP LOCKED
 )
RETURNING id, connection_id, attempt_count
`

type ClaimStuckEventsParams struct {
	StuckBefore pgtype.Timestamptz `json:"stuck_before"`
	RowLimit    int32              `json:"row_limit"`
}

type ClaimStuckEventsRow struct {
	ID           pgtype.UUID `json:"id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	AttemptCount int32       `json:"attempt_count"`
}

// Reaper: atomically re-queue events that have NO pending asynq task and are
// therefore genuinely stuck. Two cases:
//   - 'queued' older than @stuck_before — the ingest enqueue failed, so asynq
//     never received a task for it.
//   - 'in_flight' on a CLI destination — the CLI dispatch path returns
//     asynq.SkipRetry (handing off to the WS), so if the tunnel died mid-flight
//     nothing will ever retry it.
//
// HTTP 'in_flight' events are deliberately excluded: asynq owns their retry
// backoff AND their worker-death recovery, so reaping them would double-deliver
// and bypass the backoff schedule. @stuck_before must exceed the delivery + CLI
// response timeouts. FOR UPDATE OF e SKIP LOCKED lets replicas run concurrently
// without double-claiming (and locks only events, not the joined rows).
// ponytail: a pathologically low rate limit (refill > @stuck_before) could let
// a rate-limit-deferred 'queued' event be reaped early → one duplicate delivery;
// acceptable under the system's at-least-once contract.
func (q *Queries) ClaimStuckEvents(ctx context.Context, arg ClaimStuckEventsParams) ([]ClaimStuckEventsRow, error) {
	rows, err := q.db.Query(ctx, claimStuckEvents, arg.StuckBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStuckEventsRow{}
	for rows.Next() {
		var i ClaimStuckEventsRow
		if err := rows.Scan(&i.ID, &i.ConnectionID, &i.AttemptCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsByConnectionSince = `-- name: CountEventsByConnectionSince :many
SELECT e.status AS status, count(*) AS count
FROM events e
WHERE e.connection_id = $1
  AND e.org_id = $2
  AND e.is_test = FALSE
  AND e.created_at > $3::timestamptz
GROUP BY e.status
`

type CountEventsByConnectionSinceParams struct {
	ConnectionID pgtype.UUID        `json:"connection_id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Since        pgtype.Timestamptz `json:"since"`
}

type CountEventsByConnectionSinceRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Per-status event counts for one connection over a recent window, excluding
// synthetic test events so health metrics reflect real traffic. Caller passes
// the window start; folds the rows into delivered/failed/pending buckets.
func (q *Queries) CountEventsByConnectionSince(ctx context.Context, arg CountEventsByConnectionSinceParams) ([]CountEventsByConnectionSinceRow, error) {
	rows, err := q.db.Query(ctx, countEventsByConnectionSince, arg.ConnectionID, arg.OrgID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByConnectionSinceRow{}
	for rows.Next() {
		var i CountEventsByConnectionSinceRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsByOrgGroupedByConnection = `-- name: CountEventsByOrgGroupedByConnection :many
SELECT e.connection_id AS connection_id, e.status AS status, count(*) AS count
FROM events e
WHERE e.org_id = $1
  AND e.is_test = FALSE
  AND e.created_at > $2::timestamptz
GROUP BY e.connection_id, e.status
`

type CountEventsByOrgGroupedByConnectionParams struct {
	OrgID pgtype.UUID        `json:"org_id"`
	Since pgtype.Timestamptz `json:"since"`
}

type CountEventsByOrgGroupedByConnectionRow struct {
	ConnectionID pgtype.UUID `json:"connection_id"`
	Status       string      `json:"status"`
	Count        int64       `json:"count"`
}

// Per-connection, per-status counts for a whole org over a recent window,
// excluding test events. One query feeds the connections-list stat column
// (avoids an N+1 of CountEventsByConnectionSince). Handler folds by
// connection_id into delivered/failed/pending buckets.
func (q *Queries) CountEventsByOrgGroupedByConnection(ctx context.Context, arg CountEventsByOrgGroupedByConnectionParams) ([]CountEventsByOrgGroupedByConnectionRow, error) {
	rows, err := q.db.Query(ctx, countEventsByOrgGroupedByConnection, arg.OrgID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByOrgGroupedByConnectionRow{}
	for rows.Next() {
		var i CountEventsByOrgGroupedByConnectionRow
		if err := rows.Scan(&i.ConnectionID, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEventsBatch = `-- name: CreateEventsBatch :many
INSERT INTO events (request_id, connection_id, org_id, status, is_test)
SELECT $1, conn_id, $2, 'queued', $3
FROM unnest($4::uuid[]) AS conn_id
RETURNING id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at, org_id, is_test
`

type CreateEventsBatchParams struct {
	RequestID     pgtype.UUID   `json:"request_id"`
	OrgID         pgtype.UUID   `json:"org_id"`
	IsTest        bool          `json:"is_test"`
	ConnectionIds []pgtype.UUID `json:"connection_ids"`
}

// Fan-out insert: one queued event per connection_id, all sharing the same
// request_id and org_id (a source belongs to exactly one org). One statement
// instead of a roundtrip per destination. RETURNING order is not guaranteed,
// so callers key the returned rows by connection_id rather than positional
// index. @is_test is a per-request scalar (a request is wholly test or not).
func (q *Queries) CreateEventsBatch(ctx context.Context, arg CreateEventsBatchParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, createEventsBatch,
		arg.RequestID,
		arg.OrgID,
		arg.IsTest,
		arg.ConnectionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ConnectionID,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsHistogram = `-- name: EventsHistogram :many
SELECT date_trunc($1::text, e.created_at)::timestamptz AS bucket,
       e.status AS status,
       count(*) AS count
FROM events e
WHERE e.org_id = $2
  AND ($3::uuid IS NULL OR e.connection_id = $3)
  AND ($4::text        IS NULL OR e.status        = $4)
  AND e.created_at >= $5::timestamptz
GROUP BY bucket, e.status
ORDER BY bucket
`

type EventsHistogramParams struct {
	Bucket       string             `json:"bucket"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ConnectionID pgtype.UUID        `json:"connection_id"`
	Status       *string            `json:"status"`
	After        pgtype.Timestamptz `json:"after"`
}

type EventsHistogramRow struct {
	Bucket pgtype.Timestamptz `json:"bucket"`
	Status string             `json:"status"`
	Count  int64              `json:"count"`
}

// Time-bucketed event counts by status for the events-page timeline graph.
// @bucket is a date_trunc unit ('hour' | 'day' | ...) chosen by the handler
// from the selected range. Same optional connection_id/status filters as
// ListEvents so the graph tracks the table; @after bounds the window (always a
// finite range). Includes test events, matching the list view.
func (q *Queries) EventsHistogram(ctx context.Context, arg EventsHistogramParams) ([]EventsHistogramRow, error) {
	rows, err := q.db.Query(ctx, eventsHistogram,
		arg.Bucket,
		arg.OrgID,
		arg.ConnectionID,
		arg.Status,
		arg.After,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsHistogramRow{}
	for rows.Next() {
		var i EventsHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at, org_id, is_test FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.IsTest,
	)
	return i, err
}

const getEventDetailForOrg = `-- name: GetEventDetailForOrg :one
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count,
       e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.is_test,
       c.source_id      AS source_id,
       c.destination_id AS destination_id,
       d.type           AS destination_type,
       d.url            AS destination_url,
       r.http_method    AS http_method,
       r.http_path      AS http_path,
       r.headers        AS request_headers,
       r.body_ref       AS body_ref,
       r.body_size      AS body_size,
       r.content_type   AS content_type
  FROM events e
  JOIN connections c  ON c.id = e.connection_id
  JOIN destinations d ON d.id = c.destination_id
  JOIN requests r     ON r.id = e.request_id
 WHERE e.id = $1
   AND e.org_id = $2
`

type GetEventDetailForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

type GetEventDetailForOrgRow struct {
	ID              pgtype.UUID        `json:"id"`
	RequestID       pgtype.UUID        `json:"request_id"`
	ConnectionID    pgtype.UUID        `json:"connection_id"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	LastAttemptAt   pgtype.Timestamptz `json:"last_attempt_at"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsTest          bool               `json:"is_test"`
	SourceID        pgtype.UUID        `json:"source_id"`
	DestinationID   pgtype.UUID        `json:"destination_id"`
	DestinationType string             `json:"destination_type"`
	DestinationUrl  *string            `json:"destination_url"`
	HTTPMethod      string             `json:"http_method"`
	HTTPPath        string             `json:"http_path"`
	RequestHeaders  []byte             `json:"request_headers"`
	BodyRef         string             `json:"body_ref"`
	BodySize        int32              `json:"body_size"`
	ContentType     *string            `json:"content_type"`
}

// Full event view for the detail page: the event, its connection's
// source/destination, the destination endpoint, and the originating request
// (method/path/headers/body pointer). One org-scoped row that backs the
// Overview + Request-data panels.
func (q *Queries) GetEventDetailForOrg(ctx context.Context, arg GetEventDetailForOrgParams) (GetEventDetailForOrgRow, error) {
	row := q.db.QueryRow(ctx, getEventDetailForOrg, arg.ID, arg.OrgID)
	var i GetEventDetailForOrgRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
		&i.SourceID,
		&i.DestinationID,
		&i.DestinationType,
		&i.DestinationUrl,
		&i.HTTPMethod,
		&i.HTTPPath,
		&i.RequestHeaders,
		&i.BodyRef,
		&i.BodySize,
		&i.ContentType,
	)
	return i, err
}

const getEventForDelivery = `-- name: GetEventForDelivery :one
SELECT e.id              AS id,
       e.request_id      AS request_id,
       e.connection_id   AS connection_id,
       e.status          AS status,
       e.attempt_count   AS attempt_count,
       e.created_at      AS created_at,
       c.source_id       AS source_id,
       c.destination_id  AS destination_id,
       c.max_retries     AS max_retries,
       c.retry_strategy  AS retry_strategy,
       c.retry_base_ms   AS retry_base_ms,
       c.retry_cap_ms    AS retry_cap_ms,
       c.retry_jitter_pct AS retry_jitter_pct,
       c.custom_retry_schedule AS custom_retry_schedule,
       d.type            AS destination_type,
       d.url             AS destination_url,
       d.auth_config     AS destination_auth_config,
       d.rate_limit_rps  AS destination_rate_limit_rps,
       d.rate_limit_burst AS destination_rate_limit_burst,
       d.max_inflight    AS destination_max_inflight,
       r.body_ref        AS body_ref,
       r.headers         AS request_headers
FROM events e
JOIN connections c ON c.id = e.connection_id
JOIN destinations d ON d.id = c.destination_id
JOIN requests r ON r.id = e.request_id
WHERE e.id = $1
`

type GetEventForDeliveryRow struct {
	ID                        pgtype.UUID        `json:"id"`
	RequestID                 pgtype.UUID        `json:"request_id"`
	ConnectionID              pgtype.UUID        `json:"connection_id"`
	Status                    string             `json:"status"`
	AttemptCount              int32              `json:"attempt_count"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	SourceID                  pgtype.UUID        `json:"source_id"`
	DestinationID             pgtype.UUID        `json:"destination_id"`
	MaxRetries                int32              `json:"max_retries"`
	RetryStrategy             string             `json:"retry_strategy"`
	RetryBaseMs               int32              `json:"retry_base_ms"`
	RetryCapMs                int32              `json:"retry_cap_ms"`
	RetryJitterPct            int32              `json:"retry_jitter_pct"`
	CustomRetrySchedule       []byte             `json:"custom_retry_schedule"`
	DestinationType           string             `json:"destination_type"`
	DestinationUrl            *string            `json:"destination_url"`
	DestinationAuthConfig     []byte             `json:"destination_auth_config"`
	DestinationRateLimitRps   *int32             `json:"destination_rate_limit_rps"`
	DestinationRateLimitBurst *int32             `json:"destination_rate_limit_burst"`
	DestinationMaxInflight    *int32             `json:"destination_max_inflight"`
	BodyRef                   string             `json:"body_ref"`
	RequestHeaders            []byte             `json:"request_headers"`
}

func (q *Queries) GetEventForDelivery(ctx context.Context, id pgtype.UUID) (GetEventForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getEventForDelivery, id)
	var i GetEventForDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.SourceID,
		&i.DestinationID,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.DestinationType,
		&i.DestinationUrl,
		&i.DestinationAuthConfig,
		&i.DestinationRateLimitRps,
		&i.DestinationRateLimitBurst,
		&i.DestinationMaxInflight,
		&i.BodyRef,
		&i.RequestHeaders,
	)
	return i, err
}

const getEventForOrg = `-- name: GetEventForOrg :one
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.org_id, e.is_test
  FROM events e
 WHERE e.id = $1
   AND e.org_id = $2
`

type GetEventForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// org_id lives on events now, so this is a direct two-column lookup (PK + org)
// instead of a join through connections/sources.
func (q *Queries) GetEventForOrg(ctx context.Context, arg GetEventForOrgParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForOrg, arg.ID, arg.OrgID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.IsTest,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.org_id, e.is_test
FROM events e
WHERE e.org_id = $1
  AND ($2::uuid IS NULL OR e.connection_id = $2)
  AND ($3::text        IS NULL OR e.status        = $3)
  AND ($4::timestamptz  IS NULL OR e.created_at >= $4)
  AND (
    $5::timestamptz IS NULL
    OR (e.created_at, e.id) < ($5::timestamptz, $6::uuid)
  )
ORDER BY e.created_at DESC, e.id DESC
LIMIT $7
`

type ListEventsParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	ConnectionID    pgtype.UUID        `json:"connection_id"`
	Status          *string            `json:"status"`
	After           pgtype.Timestamptz `json:"after"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Keyset pagination on (created_at DESC, id DESC). Optional connection_id and
// status filters use the narg NULL-guard idiom (see audit_logs.sql): a nil
// param drops the clause. The handler passes connection_id as a Valid pgtype
// whenever the query param is present (even an all-zero UUID), so a present
// filter that matches nothing returns empty rather than falling through to
// unfiltered. events_connection_created_idx serves the connection+order path;
// events_org_created_idx the org-only path.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.OrgID,
		arg.ConnectionID,
		arg.Status,
		arg.After,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ConnectionID,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventDelivered = `-- name: MarkEventDelivered :exec
UPDATE events
SET status          = 'delivered',
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

// attempt_count is bumped once per delivery cycle by MarkEventInFlight; the
// terminal transitions must NOT increment again (that double-counted attempts
// and made recorded attempt_num values skip).
func (q *Queries) MarkEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventDelivered, id)
	return err
}

const markEventDiscarded = `-- name: MarkEventDiscarded :exec
UPDATE events
SET status        = 'discarded',
    next_retry_at = NULL,
    updated_at    = now()
WHERE id = $1
`

// Terminal state for a CLI event that waited past the tunnel deadline with no
// live listener. Unlike 'failed' it never got a delivery attempt; it's dropped
// until a user manually retries (ResetEventForManualRetry re-queues it).
func (q *Queries) MarkEventDiscarded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventDiscarded, id)
	return err
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE events
SET status          = 'failed',
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventFailed, id)
	return err
}

const markEventInFlight = `-- name: MarkEventInFlight :exec
UPDATE events
SET status          = 'in_flight',
    attempt_count   = attempt_count + 1,
    last_attempt_at = now(),
    updated_at      = now()
WHERE id = $1
`

// The single attempt_count incrementer. recordAttempt derives attempt_num from
// the pre-increment count, so this keeps attempt_num monotonic and gap-free.
func (q *Queries) MarkEventInFlight(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventInFlight, id)
	return err
}

const resetEventForManualRetry = `-- name: ResetEventForManualRetry :exec
UPDATE events
SET status        = 'queued',
    next_retry_at = NULL,
    updated_at    = now()
WHERE id = $1
`

// Do NOT reset attempt_count: zeroing it made the next attempt reuse
// attempt_num=1, colliding with the original attempt on UNIQUE(event_id,
// attempt_num) and silently dropping the retry's attempt row. Keep it monotonic;
// asynq's own retry budget is reset separately by re-enqueuing with Attempt=0.
func (q *Queries) ResetEventForManualRetry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetEventForManualRetry, id)
	return err
}

const resetEventForRetry = `-- name: ResetEventForRetry :exec
UPDATE events
SET status        = 'queued',
    next_retry_at = $2,
    updated_at    = now()
WHERE id = $1
`

type ResetEventForRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) ResetEventForRetry(ctx context.Context, arg ResetEventForRetryParams) error {
	_, err := q.db.Exec(ctx, resetEventForRetry, arg.ID, arg.NextRetryAt)
	return err
}
