// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminEventsSince = `-- name: AdminEventsSince :one
SELECT count(*)::bigint FROM events WHERE created_at >= $1::timestamptz
`

// Cross-tenant event throughput for the super-admin overview (count since @since).
func (q *Queries) AdminEventsSince(ctx context.Context, since pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, adminEventsSince, since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminTopSources = `-- name: AdminTopSources :many
SELECT s.id            AS source_id,
       s.name          AS source_name,
       count(*)::bigint AS events
FROM events e
JOIN requests r ON r.id = e.request_id
JOIN sources s ON s.id = r.source_id
WHERE e.created_at >= $1::timestamptz
GROUP BY s.id, s.name
ORDER BY events DESC
LIMIT 5
`

type AdminTopSourcesRow struct {
	SourceID   pgtype.UUID `json:"source_id"`
	SourceName string      `json:"source_name"`
	Events     int64       `json:"events"`
}

// Cross-tenant top sources by event volume since @since (source reached via the
// originating request), for the super-admin overview.
func (q *Queries) AdminTopSources(ctx context.Context, since pgtype.Timestamptz) ([]AdminTopSourcesRow, error) {
	rows, err := q.db.Query(ctx, adminTopSources, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminTopSourcesRow{}
	for rows.Next() {
		var i AdminTopSourcesRow
		if err := rows.Scan(&i.SourceID, &i.SourceName, &i.Events); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimStuckEvents = `-- name: ClaimStuckEvents :many
UPDATE events
   SET status = 'queued', next_retry_at = now(), updated_at = now()
 WHERE id IN (
   SELECT e.id
     FROM events e
     JOIN connections c  ON c.id = e.connection_id
     JOIN destinations d ON d.id = c.destination_id
    WHERE (
        (e.status = 'queued' AND e.updated_at < $1)
        OR (e.status = 'in_flight' AND d.type = 'cli' AND e.updated_at < $2)
      )
    ORDER BY e.updated_at ASC
    LIMIT $3
    FOR UPDATE OF e SKIP LOCKED
 )
RETURNING id, org_id, connection_id, attempt_count
`

type ClaimStuckEventsParams struct {
	QueuedStuckBefore pgtype.Timestamptz `json:"queued_stuck_before"`
	CliStuckBefore    pgtype.Timestamptz `json:"cli_stuck_before"`
	RowLimit          int32              `json:"row_limit"`
}

type ClaimStuckEventsRow struct {
	ID           pgtype.UUID `json:"id"`
	OrgID        pgtype.UUID `json:"org_id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
	AttemptCount int32       `json:"attempt_count"`
}

// Reaper: atomically re-queue events that never entered the dqueue or lost their
// owner, and are therefore genuinely stuck. Two cases with SEPARATE staleness
// windows because they have very different safe thresholds:
//   - 'queued' older than @queued_stuck_before — the ingest Enqueue failed, so
//     the event was never put on the dqueue. This window is WIDE: a still-'queued'
//     event that is merely slow or being repeatedly rate-limit/in-flight deferred
//     (defer_ reschedules via the scheduled ZSET without bumping updated_at) is
//     making legitimate progress, and re-queuing it mints a duplicate copy the
//     terminal-status guard in Process cannot catch (both copies are non-terminal).
//     So the window must exceed the delivery lease + defer churn.
//   - 'in_flight' on a CLI destination older than @cli_stuck_before — the CLI
//     dispatch path Acks the leased member at handoff to the WS tunnel, so if the
//     tunnel died mid-flight nothing owns the event any more. The reaper is its
//     only recovery, so this window is SHORT (just past the CLI response timeout).
//
// HTTP 'in_flight' events are deliberately excluded: the dqueue recoverer (the
// dq:processing lease) plus the scheduled ZSET own their retry backoff AND their
// worker-death recovery, so reaping them would double-deliver and bypass the
// backoff schedule. FOR UPDATE OF e SKIP LOCKED lets replicas run concurrently
// without double-claiming (and locks only events, not the joined rows).
// ponytail: a destination rate-limited continuously for longer than
// @queued_stuck_before still yields one duplicate re-enqueue per window;
// acceptable under the system's at-least-once contract.
func (q *Queries) ClaimStuckEvents(ctx context.Context, arg ClaimStuckEventsParams) ([]ClaimStuckEventsRow, error) {
	rows, err := q.db.Query(ctx, claimStuckEvents, arg.QueuedStuckBefore, arg.CliStuckBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimStuckEventsRow{}
	for rows.Next() {
		var i ClaimStuckEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ConnectionID,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsByConnectionSince = `-- name: CountEventsByConnectionSince :many
SELECT e.status AS status, count(*) AS count
FROM events e
WHERE e.connection_id = $1
  AND e.org_id = $2
  AND e.is_test = FALSE
  AND e.created_at > $3::timestamptz
GROUP BY e.status
`

type CountEventsByConnectionSinceParams struct {
	ConnectionID pgtype.UUID        `json:"connection_id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Since        pgtype.Timestamptz `json:"since"`
}

type CountEventsByConnectionSinceRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// Per-status event counts for one connection over a recent window, excluding
// synthetic test events so health metrics reflect real traffic. Caller passes
// the window start; folds the rows into delivered/failed/pending buckets.
func (q *Queries) CountEventsByConnectionSince(ctx context.Context, arg CountEventsByConnectionSinceParams) ([]CountEventsByConnectionSinceRow, error) {
	rows, err := q.db.Query(ctx, countEventsByConnectionSince, arg.ConnectionID, arg.OrgID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByConnectionSinceRow{}
	for rows.Next() {
		var i CountEventsByConnectionSinceRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsByOrgGroupedByConnection = `-- name: CountEventsByOrgGroupedByConnection :many
SELECT e.connection_id AS connection_id, e.status AS status, count(*) AS count
FROM events e
WHERE e.org_id = $1
  AND e.is_test = FALSE
  AND e.created_at > $2::timestamptz
GROUP BY e.connection_id, e.status
`

type CountEventsByOrgGroupedByConnectionParams struct {
	OrgID pgtype.UUID        `json:"org_id"`
	Since pgtype.Timestamptz `json:"since"`
}

type CountEventsByOrgGroupedByConnectionRow struct {
	ConnectionID pgtype.UUID `json:"connection_id"`
	Status       string      `json:"status"`
	Count        int64       `json:"count"`
}

// Per-connection, per-status counts for a whole org over a recent window,
// excluding test events. One query feeds the connections-list stat column
// (avoids an N+1 of CountEventsByConnectionSince). Handler folds by
// connection_id into delivered/failed/pending buckets.
func (q *Queries) CountEventsByOrgGroupedByConnection(ctx context.Context, arg CountEventsByOrgGroupedByConnectionParams) ([]CountEventsByOrgGroupedByConnectionRow, error) {
	rows, err := q.db.Query(ctx, countEventsByOrgGroupedByConnection, arg.OrgID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByOrgGroupedByConnectionRow{}
	for rows.Next() {
		var i CountEventsByOrgGroupedByConnectionRow
		if err := rows.Scan(&i.ConnectionID, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEventsBatch = `-- name: CreateEventsBatch :many
INSERT INTO events (request_id, connection_id, org_id, status, is_test)
SELECT $1, conn_id, $2, 'queued', $3
FROM unnest($4::uuid[]) AS conn_id
RETURNING id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at, org_id, is_test
`

type CreateEventsBatchParams struct {
	RequestID     pgtype.UUID   `json:"request_id"`
	OrgID         pgtype.UUID   `json:"org_id"`
	IsTest        bool          `json:"is_test"`
	ConnectionIds []pgtype.UUID `json:"connection_ids"`
}

// Fan-out insert: one queued event per connection_id, all sharing the same
// request_id and org_id (a source belongs to exactly one org). One statement
// instead of a roundtrip per destination. RETURNING order is not guaranteed,
// so callers key the returned rows by connection_id rather than positional
// index. @is_test is a per-request scalar (a request is wholly test or not).
func (q *Queries) CreateEventsBatch(ctx context.Context, arg CreateEventsBatchParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, createEventsBatch,
		arg.RequestID,
		arg.OrgID,
		arg.IsTest,
		arg.ConnectionIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ConnectionID,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const destinationDeliveryHistogram = `-- name: DestinationDeliveryHistogram :many
WITH series AS (
  SELECT gs AS bucket
  FROM generate_series(
    date_trunc($1::text, $2::timestamptz),
    date_trunc($1::text, now()),
    ('1 ' || $1::text)::interval
  ) AS gs
),
counts AS (
  SELECT date_trunc($1::text, e.created_at) AS bucket, e.status AS status, count(*) AS count
  FROM events e
  JOIN connections c ON c.id = e.connection_id
  WHERE c.destination_id = $3
    AND e.org_id = $4
    AND e.created_at >= $2::timestamptz
  GROUP BY 1, 2
)
SELECT s.bucket::timestamptz     AS bucket,
       c.status                  AS status,
       coalesce(c.count, 0)::bigint AS count
FROM series s
LEFT JOIN counts c ON c.bucket = s.bucket
ORDER BY s.bucket
`

type DestinationDeliveryHistogramParams struct {
	Bucket        string             `json:"bucket"`
	After         pgtype.Timestamptz `json:"after"`
	DestinationID pgtype.UUID        `json:"destination_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
}

type DestinationDeliveryHistogramRow struct {
	Bucket pgtype.Timestamptz `json:"bucket"`
	Status *string            `json:"status"`
	Count  int64              `json:"count"`
}

// Gap-filled delivery outcomes over time for ONE destination. Events reach a
// destination through their connection, so join connections to filter. Same
// generate_series gap-fill + UTC buckets as EventsHistogram; empty buckets come
// back as a NULL-status row with count 0.
func (q *Queries) DestinationDeliveryHistogram(ctx context.Context, arg DestinationDeliveryHistogramParams) ([]DestinationDeliveryHistogramRow, error) {
	rows, err := q.db.Query(ctx, destinationDeliveryHistogram,
		arg.Bucket,
		arg.After,
		arg.DestinationID,
		arg.OrgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DestinationDeliveryHistogramRow{}
	for rows.Next() {
		var i DestinationDeliveryHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const destinationDeliveryStats = `-- name: DestinationDeliveryStats :one
SELECT
  count(*)::bigint AS total,
  count(*) FILTER (WHERE e.status = 'delivered')::bigint AS delivered,
  coalesce((SELECT avg(a.duration_ms)
   FROM attempts a
   JOIN events e2 ON e2.id = a.event_id
   JOIN connections c2 ON c2.id = e2.connection_id
   WHERE c2.destination_id = $1
     AND e2.org_id = $2
     AND a.attempted_at >= $3::timestamptz
     AND a.duration_ms IS NOT NULL), 0)::float8 AS avg_latency_ms,
  -- Count of timed attempts so the handler can distinguish "genuinely ~0ms"
  -- from "no completed attempts" and emit null (—) not a misleading 0 (audit N4).
  (SELECT count(*)
   FROM attempts a
   JOIN events e2 ON e2.id = a.event_id
   JOIN connections c2 ON c2.id = e2.connection_id
   WHERE c2.destination_id = $1
     AND e2.org_id = $2
     AND a.attempted_at >= $3::timestamptz
     AND a.duration_ms IS NOT NULL)::bigint AS latency_samples
FROM events e
JOIN connections c ON c.id = e.connection_id
WHERE c.destination_id = $1
  AND e.org_id = $2
  AND e.created_at >= $3::timestamptz
`

type DestinationDeliveryStatsParams struct {
	DestinationID pgtype.UUID        `json:"destination_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	After         pgtype.Timestamptz `json:"after"`
}

type DestinationDeliveryStatsRow struct {
	Total          int64   `json:"total"`
	Delivered      int64   `json:"delivered"`
	AvgLatencyMs   float64 `json:"avg_latency_ms"`
	LatencySamples int64   `json:"latency_samples"`
}

// Window totals for the delivery-rate + avg-latency cards. delivered/total gives
// the rate; avg_latency_ms averages the delivery HTTP call time recorded per
// attempt (NULL when no completed attempts in the window).
func (q *Queries) DestinationDeliveryStats(ctx context.Context, arg DestinationDeliveryStatsParams) (DestinationDeliveryStatsRow, error) {
	row := q.db.QueryRow(ctx, destinationDeliveryStats, arg.DestinationID, arg.OrgID, arg.After)
	var i DestinationDeliveryStatsRow
	err := row.Scan(
		&i.Total,
		&i.Delivered,
		&i.AvgLatencyMs,
		&i.LatencySamples,
	)
	return i, err
}

const eventsHistogram = `-- name: EventsHistogram :many
WITH series AS (
  SELECT gs AS bucket
  FROM generate_series(
    date_trunc($1::text, $2::timestamptz),
    date_trunc($1::text, now()),
    ('1 ' || $1::text)::interval
  ) AS gs
),
counts AS (
  SELECT date_trunc($1::text, e.created_at) AS bucket,
         e.status AS status,
         count(*) AS count
  FROM events e
  WHERE e.org_id = $3
    AND ($4::uuid IS NULL OR e.connection_id = $4)
    AND ($5::text        IS NULL OR e.status        = $5)
    AND e.created_at >= $2::timestamptz
  GROUP BY 1, 2
)
SELECT s.bucket::timestamptz     AS bucket,
       c.status                  AS status,
       coalesce(c.count, 0)::bigint AS count
FROM series s
LEFT JOIN counts c ON c.bucket = s.bucket
ORDER BY s.bucket
`

type EventsHistogramParams struct {
	Bucket       string             `json:"bucket"`
	After        pgtype.Timestamptz `json:"after"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ConnectionID pgtype.UUID        `json:"connection_id"`
	Status       *string            `json:"status"`
}

type EventsHistogramRow struct {
	Bucket pgtype.Timestamptz `json:"bucket"`
	Status *string            `json:"status"`
	Count  int64              `json:"count"`
}

// Time-bucketed event counts by status for the events-page timeline graph.
// @bucket is a date_trunc unit ('minute' | 'hour' | 'day' | 'week') chosen by
// the handler from the selected range. The series is GAP-FILLED in SQL:
// generate_series emits every bucket from date_trunc(@after) through now(), so
// quiet buckets come back as one row with a NULL status and count 0 — the client
// plots the rows as-is, no reconstruction. Buckets are UTC-aligned. Same optional
// connection_id/status filters as ListEvents; includes test events.
func (q *Queries) EventsHistogram(ctx context.Context, arg EventsHistogramParams) ([]EventsHistogramRow, error) {
	rows, err := q.db.Query(ctx, eventsHistogram,
		arg.Bucket,
		arg.After,
		arg.OrgID,
		arg.ConnectionID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventsHistogramRow{}
	for rows.Next() {
		var i EventsHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at, org_id, is_test FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.IsTest,
	)
	return i, err
}

const getEventDetailForOrg = `-- name: GetEventDetailForOrg :one
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count,
       e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.is_test,
       c.source_id      AS source_id,
       c.destination_id AS destination_id,
       d.type           AS destination_type,
       d.url            AS destination_url,
       r.http_method    AS http_method,
       r.http_path      AS http_path,
       r.headers        AS request_headers,
       r.body_ref       AS body_ref,
       r.body_size      AS body_size,
       r.content_type   AS content_type
  FROM events e
  JOIN connections c  ON c.id = e.connection_id
  JOIN destinations d ON d.id = c.destination_id
  JOIN requests r     ON r.id = e.request_id
 WHERE e.id = $1
   AND e.org_id = $2
`

type GetEventDetailForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

type GetEventDetailForOrgRow struct {
	ID              pgtype.UUID        `json:"id"`
	RequestID       pgtype.UUID        `json:"request_id"`
	ConnectionID    pgtype.UUID        `json:"connection_id"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	LastAttemptAt   pgtype.Timestamptz `json:"last_attempt_at"`
	NextRetryAt     pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsTest          bool               `json:"is_test"`
	SourceID        pgtype.UUID        `json:"source_id"`
	DestinationID   pgtype.UUID        `json:"destination_id"`
	DestinationType string             `json:"destination_type"`
	DestinationUrl  *string            `json:"destination_url"`
	HTTPMethod      string             `json:"http_method"`
	HTTPPath        string             `json:"http_path"`
	RequestHeaders  []byte             `json:"request_headers"`
	BodyRef         string             `json:"body_ref"`
	BodySize        int32              `json:"body_size"`
	ContentType     *string            `json:"content_type"`
}

// Full event view for the detail page: the event, its connection's
// source/destination, the destination endpoint, and the originating request
// (method/path/headers/body pointer). One org-scoped row that backs the
// Overview + Request-data panels.
func (q *Queries) GetEventDetailForOrg(ctx context.Context, arg GetEventDetailForOrgParams) (GetEventDetailForOrgRow, error) {
	row := q.db.QueryRow(ctx, getEventDetailForOrg, arg.ID, arg.OrgID)
	var i GetEventDetailForOrgRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsTest,
		&i.SourceID,
		&i.DestinationID,
		&i.DestinationType,
		&i.DestinationUrl,
		&i.HTTPMethod,
		&i.HTTPPath,
		&i.RequestHeaders,
		&i.BodyRef,
		&i.BodySize,
		&i.ContentType,
	)
	return i, err
}

const getEventForDelivery = `-- name: GetEventForDelivery :one
SELECT e.id              AS id,
       e.request_id      AS request_id,
       e.connection_id   AS connection_id,
       e.status          AS status,
       e.attempt_count   AS attempt_count,
       e.created_at      AS created_at,
       e.org_id          AS org_id,
       c.source_id       AS source_id,
       c.destination_id  AS destination_id,
       c.max_retries     AS max_retries,
       c.retry_strategy  AS retry_strategy,
       c.retry_base_ms   AS retry_base_ms,
       c.retry_cap_ms    AS retry_cap_ms,
       c.retry_jitter_pct AS retry_jitter_pct,
       c.custom_retry_schedule AS custom_retry_schedule,
       d.type            AS destination_type,
       d.url             AS destination_url,
       d.auth_config     AS destination_auth_config,
       d.rate_limit_rps  AS destination_rate_limit_rps,
       d.rate_limit_burst AS destination_rate_limit_burst,
       d.max_inflight    AS destination_max_inflight,
       r.body_ref        AS body_ref,
       r.headers         AS request_headers
FROM events e
JOIN connections c ON c.id = e.connection_id
JOIN destinations d ON d.id = c.destination_id
JOIN requests r ON r.id = e.request_id
WHERE e.id = $1
`

type GetEventForDeliveryRow struct {
	ID                        pgtype.UUID        `json:"id"`
	RequestID                 pgtype.UUID        `json:"request_id"`
	ConnectionID              pgtype.UUID        `json:"connection_id"`
	Status                    string             `json:"status"`
	AttemptCount              int32              `json:"attempt_count"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	OrgID                     pgtype.UUID        `json:"org_id"`
	SourceID                  pgtype.UUID        `json:"source_id"`
	DestinationID             pgtype.UUID        `json:"destination_id"`
	MaxRetries                int32              `json:"max_retries"`
	RetryStrategy             string             `json:"retry_strategy"`
	RetryBaseMs               int32              `json:"retry_base_ms"`
	RetryCapMs                int32              `json:"retry_cap_ms"`
	RetryJitterPct            int32              `json:"retry_jitter_pct"`
	CustomRetrySchedule       []byte             `json:"custom_retry_schedule"`
	DestinationType           string             `json:"destination_type"`
	DestinationUrl            *string            `json:"destination_url"`
	DestinationAuthConfig     []byte             `json:"destination_auth_config"`
	DestinationRateLimitRps   *int32             `json:"destination_rate_limit_rps"`
	DestinationRateLimitBurst *int32             `json:"destination_rate_limit_burst"`
	DestinationMaxInflight    *int32             `json:"destination_max_inflight"`
	BodyRef                   string             `json:"body_ref"`
	RequestHeaders            []byte             `json:"request_headers"`
}

func (q *Queries) GetEventForDelivery(ctx context.Context, id pgtype.UUID) (GetEventForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getEventForDelivery, id)
	var i GetEventForDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.OrgID,
		&i.SourceID,
		&i.DestinationID,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.DestinationType,
		&i.DestinationUrl,
		&i.DestinationAuthConfig,
		&i.DestinationRateLimitRps,
		&i.DestinationRateLimitBurst,
		&i.DestinationMaxInflight,
		&i.BodyRef,
		&i.RequestHeaders,
	)
	return i, err
}

const getEventForOrg = `-- name: GetEventForOrg :one
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.org_id, e.is_test
  FROM events e
 WHERE e.id = $1
   AND e.org_id = $2
`

type GetEventForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// org_id lives on events now, so this is a direct two-column lookup (PK + org)
// instead of a join through connections/sources.
func (q *Queries) GetEventForOrg(ctx context.Context, arg GetEventForOrgParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForOrg, arg.ID, arg.OrgID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgID,
		&i.IsTest,
	)
	return i, err
}

const hotDestinations = `-- name: HotDestinations :many
SELECT d.id                                                        AS destination_id,
       d.name                                                      AS destination_name,
       count(*)::bigint                                            AS total,
       count(*) FILTER (WHERE e.status IN ('failed', 'dead'))::bigint AS failed
FROM events e
JOIN connections c ON c.id = e.connection_id
JOIN destinations d ON d.id = c.destination_id
WHERE e.created_at >= now() - interval '24 hours'
GROUP BY d.id, d.name
HAVING count(*) FILTER (WHERE e.status IN ('failed', 'dead')) > 0
ORDER BY failed DESC, total DESC
LIMIT 20
`

type HotDestinationsRow struct {
	DestinationID   pgtype.UUID `json:"destination_id"`
	DestinationName string      `json:"destination_name"`
	Total           int64       `json:"total"`
	Failed          int64       `json:"failed"`
}

// Cross-tenant (super-admin console): destinations with delivery failures in the
// last 24h, worst first. total/failed let the handler compute a failure rate.
// Only destinations that actually failed are returned (HAVING).
func (q *Queries) HotDestinations(ctx context.Context) ([]HotDestinationsRow, error) {
	rows, err := q.db.Query(ctx, hotDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotDestinationsRow{}
	for rows.Next() {
		var i HotDestinationsRow
		if err := rows.Scan(
			&i.DestinationID,
			&i.DestinationName,
			&i.Total,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at, e.org_id, e.is_test
FROM events e
WHERE e.org_id = $1
  AND ($2::uuid IS NULL OR e.connection_id = $2)
  AND ($3::text        IS NULL OR e.status        = $3)
  AND ($4::timestamptz  IS NULL OR e.created_at >= $4)
  AND (
    $5::timestamptz IS NULL
    OR (e.created_at, e.id) < ($5::timestamptz, $6::uuid)
  )
ORDER BY e.created_at DESC, e.id DESC
LIMIT $7
`

type ListEventsParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	ConnectionID    pgtype.UUID        `json:"connection_id"`
	Status          *string            `json:"status"`
	After           pgtype.Timestamptz `json:"after"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

// Keyset pagination on (created_at DESC, id DESC). Optional connection_id and
// status filters use the narg NULL-guard idiom (see audit_logs.sql): a nil
// param drops the clause. The handler passes connection_id as a Valid pgtype
// whenever the query param is present (even an all-zero UUID), so a present
// filter that matches nothing returns empty rather than falling through to
// unfiltered. events_connection_created_idx serves the connection+order path;
// events_org_created_idx the org-only path.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.OrgID,
		arg.ConnectionID,
		arg.Status,
		arg.After,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ConnectionID,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgID,
			&i.IsTest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventDelivered = `-- name: MarkEventDelivered :exec
UPDATE events
SET status          = 'delivered',
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

// attempt_count is bumped once per delivery cycle by MarkEventInFlight; the
// terminal transitions must NOT increment again (that double-counted attempts
// and made recorded attempt_num values skip).
func (q *Queries) MarkEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventDelivered, id)
	return err
}

const markEventDiscarded = `-- name: MarkEventDiscarded :exec
UPDATE events
SET status        = 'discarded',
    next_retry_at = NULL,
    updated_at    = now()
WHERE id = $1
`

// Terminal state for a CLI event that waited past the tunnel deadline with no
// live listener. Unlike 'failed' it never got a delivery attempt; it's dropped
// until a user manually retries (ResetEventForManualRetry re-queues it).
func (q *Queries) MarkEventDiscarded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventDiscarded, id)
	return err
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE events
SET status          = 'failed',
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventFailed, id)
	return err
}

const markEventInFlight = `-- name: MarkEventInFlight :exec
UPDATE events
SET status          = 'in_flight',
    attempt_count   = attempt_count + 1,
    last_attempt_at = now(),
    updated_at      = now()
WHERE id = $1
`

// The single attempt_count incrementer. recordAttempt derives attempt_num from
// the pre-increment count, so this keeps attempt_num monotonic and gap-free.
func (q *Queries) MarkEventInFlight(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventInFlight, id)
	return err
}

const resetEventForManualRetry = `-- name: ResetEventForManualRetry :exec
UPDATE events
SET status        = 'queued',
    next_retry_at = NULL,
    updated_at    = now()
WHERE id = $1
`

// Do NOT reset attempt_count: zeroing it made the next attempt reuse
// attempt_num=1, colliding with the original attempt on UNIQUE(event_id,
// attempt_num) and silently dropping the retry's attempt row. Keep it monotonic;
// the fair-queue retry counter resets separately by re-enqueuing with Attempt=0.
func (q *Queries) ResetEventForManualRetry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetEventForManualRetry, id)
	return err
}

const resetEventForRetry = `-- name: ResetEventForRetry :exec
UPDATE events
SET status        = 'queued',
    next_retry_at = $2,
    updated_at    = now()
WHERE id = $1
`

type ResetEventForRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) ResetEventForRetry(ctx context.Context, arg ResetEventForRetryParams) error {
	_, err := q.db.Exec(ctx, resetEventForRetry, arg.ID, arg.NextRetryAt)
	return err
}

const sourceRequestHistogram = `-- name: SourceRequestHistogram :many
WITH series AS (
  SELECT gs AS bucket
  FROM generate_series(
    date_trunc($1::text, $2::timestamptz),
    date_trunc($1::text, now()),
    ('1 ' || $1::text)::interval
  ) AS gs
),
counts AS (
  SELECT date_trunc($1::text, r.received_at) AS bucket, count(*) AS count
  FROM requests r
  JOIN sources s ON s.id = r.source_id
  WHERE r.source_id = $3
    AND s.org_id = $4
    AND r.received_at >= $2::timestamptz
  GROUP BY 1
)
SELECT s.bucket::timestamptz     AS bucket,
       coalesce(c.count, 0)::bigint AS count
FROM series s
LEFT JOIN counts c ON c.bucket = s.bucket
ORDER BY s.bucket
`

type SourceRequestHistogramParams struct {
	Bucket   string             `json:"bucket"`
	After    pgtype.Timestamptz `json:"after"`
	SourceID pgtype.UUID        `json:"source_id"`
	OrgID    pgtype.UUID        `json:"org_id"`
}

type SourceRequestHistogramRow struct {
	Bucket pgtype.Timestamptz `json:"bucket"`
	Count  int64              `json:"count"`
}

// Gap-filled ingest-request volume over time for ONE source (single series, no
// status dimension). Same gap-fill contract as the delivery histogram.
func (q *Queries) SourceRequestHistogram(ctx context.Context, arg SourceRequestHistogramParams) ([]SourceRequestHistogramRow, error) {
	rows, err := q.db.Query(ctx, sourceRequestHistogram,
		arg.Bucket,
		arg.After,
		arg.SourceID,
		arg.OrgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceRequestHistogramRow{}
	for rows.Next() {
		var i SourceRequestHistogramRow
		if err := rows.Scan(&i.Bucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourceRequestStats = `-- name: SourceRequestStats :one
SELECT
  (SELECT count(*) FROM requests r
   JOIN sources s ON s.id = r.source_id
   WHERE r.source_id = $1 AND s.org_id = $2
     AND r.received_at >= $3::timestamptz)::bigint AS requests,
  (SELECT count(*) FROM events e
   JOIN requests r ON r.id = e.request_id
   WHERE r.source_id = $1 AND e.org_id = $2
     AND e.created_at >= $3::timestamptz)::bigint AS events
`

type SourceRequestStatsParams struct {
	SourceID pgtype.UUID        `json:"source_id"`
	OrgID    pgtype.UUID        `json:"org_id"`
	After    pgtype.Timestamptz `json:"after"`
}

type SourceRequestStatsRow struct {
	Requests int64 `json:"requests"`
	Events   int64 `json:"events"`
}

// Window totals for the requests-rate + avg-events-per-request (fan-out) cards.
func (q *Queries) SourceRequestStats(ctx context.Context, arg SourceRequestStatsParams) (SourceRequestStatsRow, error) {
	row := q.db.QueryRow(ctx, sourceRequestStats, arg.SourceID, arg.OrgID, arg.After)
	var i SourceRequestStatsRow
	err := row.Scan(&i.Requests, &i.Events)
	return i, err
}
