// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (request_id, connection_id, status)
VALUES ($1, $2, 'queued')
RETURNING id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at
`

type CreateEventParams struct {
	RequestID    pgtype.UUID `json:"request_id"`
	ConnectionID pgtype.UUID `json:"connection_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.RequestID, arg.ConnectionID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, request_id, connection_id, status, attempt_count, last_attempt_at, next_retry_at, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventForDelivery = `-- name: GetEventForDelivery :one
SELECT e.id              AS id,
       e.request_id      AS request_id,
       e.connection_id   AS connection_id,
       e.status          AS status,
       e.attempt_count   AS attempt_count,
       c.source_id       AS source_id,
       c.destination_id  AS destination_id,
       c.max_retries     AS max_retries,
       c.retry_strategy  AS retry_strategy,
       c.retry_base_ms   AS retry_base_ms,
       c.retry_cap_ms    AS retry_cap_ms,
       c.retry_jitter_pct AS retry_jitter_pct,
       c.custom_retry_schedule AS custom_retry_schedule,
       d.type            AS destination_type,
       d.url             AS destination_url,
       d.auth_config     AS destination_auth_config,
       d.rate_limit_rps  AS destination_rate_limit_rps,
       d.rate_limit_burst AS destination_rate_limit_burst,
       d.max_inflight    AS destination_max_inflight,
       r.body_ref        AS body_ref,
       r.headers         AS request_headers
FROM events e
JOIN connections c ON c.id = e.connection_id
JOIN destinations d ON d.id = c.destination_id
JOIN requests r ON r.id = e.request_id
WHERE e.id = $1
`

type GetEventForDeliveryRow struct {
	ID                        pgtype.UUID `json:"id"`
	RequestID                 pgtype.UUID `json:"request_id"`
	ConnectionID              pgtype.UUID `json:"connection_id"`
	Status                    string      `json:"status"`
	AttemptCount              int32       `json:"attempt_count"`
	SourceID                  pgtype.UUID `json:"source_id"`
	DestinationID             pgtype.UUID `json:"destination_id"`
	MaxRetries                int32       `json:"max_retries"`
	RetryStrategy             string      `json:"retry_strategy"`
	RetryBaseMs               int32       `json:"retry_base_ms"`
	RetryCapMs                int32       `json:"retry_cap_ms"`
	RetryJitterPct            int32       `json:"retry_jitter_pct"`
	CustomRetrySchedule       []byte      `json:"custom_retry_schedule"`
	DestinationType           string      `json:"destination_type"`
	DestinationUrl            *string     `json:"destination_url"`
	DestinationAuthConfig     []byte      `json:"destination_auth_config"`
	DestinationRateLimitRps   *int32      `json:"destination_rate_limit_rps"`
	DestinationRateLimitBurst *int32      `json:"destination_rate_limit_burst"`
	DestinationMaxInflight    *int32      `json:"destination_max_inflight"`
	BodyRef                   string      `json:"body_ref"`
	RequestHeaders            []byte      `json:"request_headers"`
}

func (q *Queries) GetEventForDelivery(ctx context.Context, id pgtype.UUID) (GetEventForDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getEventForDelivery, id)
	var i GetEventForDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.SourceID,
		&i.DestinationID,
		&i.MaxRetries,
		&i.RetryStrategy,
		&i.RetryBaseMs,
		&i.RetryCapMs,
		&i.RetryJitterPct,
		&i.CustomRetrySchedule,
		&i.DestinationType,
		&i.DestinationUrl,
		&i.DestinationAuthConfig,
		&i.DestinationRateLimitRps,
		&i.DestinationRateLimitBurst,
		&i.DestinationMaxInflight,
		&i.BodyRef,
		&i.RequestHeaders,
	)
	return i, err
}

const getEventForOrg = `-- name: GetEventForOrg :one
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at
  FROM events e
  JOIN connections c ON c.id = e.connection_id
  JOIN sources s     ON s.id = c.source_id
 WHERE e.id = $1
   AND s.org_id = $2
`

type GetEventForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetEventForOrg(ctx context.Context, arg GetEventForOrgParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForOrg, arg.ID, arg.OrgID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ConnectionID,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByOrg = `-- name: ListEventsByOrg :many
SELECT e.id, e.request_id, e.connection_id, e.status, e.attempt_count, e.last_attempt_at, e.next_retry_at, e.created_at, e.updated_at
FROM events e
JOIN connections c ON c.id = e.connection_id
JOIN sources s     ON s.id = c.source_id
WHERE s.org_id = $1
ORDER BY e.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsByOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListEventsByOrg(ctx context.Context, arg ListEventsByOrgParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ConnectionID,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventDelivered = `-- name: MarkEventDelivered :exec
UPDATE events
SET status          = 'delivered',
    attempt_count   = attempt_count + 1,
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkEventDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventDelivered, id)
	return err
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE events
SET status          = 'failed',
    attempt_count   = attempt_count + 1,
    last_attempt_at = now(),
    next_retry_at   = NULL,
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventFailed, id)
	return err
}

const markEventInFlight = `-- name: MarkEventInFlight :exec
UPDATE events
SET status          = 'in_flight',
    attempt_count   = attempt_count + 1,
    last_attempt_at = now(),
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkEventInFlight(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventInFlight, id)
	return err
}

const resetEventForManualRetry = `-- name: ResetEventForManualRetry :exec
UPDATE events
SET status        = 'queued',
    attempt_count = 0,
    next_retry_at = NULL,
    updated_at    = now()
WHERE id = $1
`

func (q *Queries) ResetEventForManualRetry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetEventForManualRetry, id)
	return err
}

const resetEventForRetry = `-- name: ResetEventForRetry :exec
UPDATE events
SET status        = 'queued',
    next_retry_at = $2,
    updated_at    = now()
WHERE id = $1
`

type ResetEventForRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) ResetEventForRetry(ctx context.Context, arg ResetEventForRetryParams) error {
	_, err := q.db.Exec(ctx, resetEventForRetry, arg.ID, arg.NextRetryAt)
	return err
}
