// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_types.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_types (org_id, name, description, schema)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, description, schema, archived, created_at, updated_at
`

type CreateEventTypeParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Schema      []byte      `json:"schema"`
}

func (q *Queries) CreateEventType(ctx context.Context, arg CreateEventTypeParams) (EventType, error) {
	row := q.db.QueryRow(ctx, createEventType,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Schema,
	)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventTypeForOrg = `-- name: DeleteEventTypeForOrg :one
DELETE FROM event_types WHERE org_id = $1 AND name = $2 RETURNING id
`

type DeleteEventTypeForOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

func (q *Queries) DeleteEventTypeForOrg(ctx context.Context, arg DeleteEventTypeForOrgParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEventTypeForOrg, arg.OrgID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEventTypeForOrg = `-- name: GetEventTypeForOrg :one
SELECT id, org_id, name, description, schema, archived, created_at, updated_at FROM event_types WHERE org_id = $1 AND name = $2
`

type GetEventTypeForOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

func (q *Queries) GetEventTypeForOrg(ctx context.Context, arg GetEventTypeForOrgParams) (EventType, error) {
	row := q.db.QueryRow(ctx, getEventTypeForOrg, arg.OrgID, arg.Name)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventTypesByOrg = `-- name: ListEventTypesByOrg :many
SELECT id, org_id, name, description, schema, archived, created_at, updated_at FROM event_types WHERE org_id = $1 ORDER BY name ASC LIMIT $2
`

type ListEventTypesByOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListEventTypesByOrg(ctx context.Context, arg ListEventTypesByOrgParams) ([]EventType, error) {
	rows, err := q.db.Query(ctx, listEventTypesByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventType{}
	for rows.Next() {
		var i EventType
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Schema,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventType = `-- name: UpdateEventType :one
UPDATE event_types
   SET description = COALESCE($1, description),
       schema      = COALESCE($2::jsonb, schema),
       archived    = COALESCE($3, archived),
       updated_at  = now()
 WHERE org_id = $4 AND name = $5
 RETURNING id, org_id, name, description, schema, archived, created_at, updated_at
`

type UpdateEventTypeParams struct {
	Description *string     `json:"description"`
	Schema      []byte      `json:"schema"`
	Archived    *bool       `json:"archived"`
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
}

func (q *Queries) UpdateEventType(ctx context.Context, arg UpdateEventTypeParams) (EventType, error) {
	row := q.db.QueryRow(ctx, updateEventType,
		arg.Description,
		arg.Schema,
		arg.Archived,
		arg.OrgID,
		arg.Name,
	)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Schema,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
