// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role) VALUES ($1, $2, $3)
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const bumpUserSessionEpoch = `-- name: BumpUserSessionEpoch :exec
UPDATE users SET session_epoch = session_epoch + 1, updated_at = now() WHERE id = $1
`

// Invalidate all of a user's outstanding signed session cookies by advancing
// their epoch. Used by logout (logout-all) and future disable/security flows.
func (q *Queries) BumpUserSessionEpoch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpUserSessionEpoch, id)
	return err
}

const countOrgMembershipsForUser = `-- name: CountOrgMembershipsForUser :one
SELECT count(*) FROM org_members WHERE user_id = $1
`

func (q *Queries) CountOrgMembershipsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgMembershipsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id, email, name, is_super_admin, created_at, updated_at, session_epoch
`

type CreateUserParams struct {
	Email string  `json:"email"`
	Name  *string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionEpoch,
	)
	return i, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	return err
}

const deleteOrgOwnerIfNotLast = `-- name: DeleteOrgOwnerIfNotLast :execrows
DELETE FROM org_members m
 WHERE m.org_id = $1
   AND m.user_id = $2
   AND m.role = 'owner'
   AND (
     SELECT count(*) FROM org_members om
      WHERE om.org_id = $1 AND om.role = 'owner'
   ) > 1
`

type DeleteOrgOwnerIfNotLastParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Atomic remove: delete the owner row ONLY IF at least one other owner
// remains. Same race-free invariant as DemoteOrgOwnerIfNotLast.
func (q *Queries) DeleteOrgOwnerIfNotLast(ctx context.Context, arg DeleteOrgOwnerIfNotLastParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrgOwnerIfNotLast, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const demoteOrgOwnerIfNotLast = `-- name: DemoteOrgOwnerIfNotLast :execrows
UPDATE org_members m
   SET role = $3
 WHERE m.org_id = $1
   AND m.user_id = $2
   AND m.role = 'owner'
   AND (
     SELECT count(*) FROM org_members om
      WHERE om.org_id = $1 AND om.role = 'owner'
   ) > 1
`

type DemoteOrgOwnerIfNotLastParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

// Atomic demote: change role to $3 ONLY IF at least one other owner
// remains. The whole operation is one statement, so two concurrent
// demote requests can't both pass a count-then-update race.
func (q *Queries) DemoteOrgOwnerIfNotLast(ctx context.Context, arg DemoteOrgOwnerIfNotLastParams) (int64, error) {
	result, err := q.db.Exec(ctx, demoteOrgOwnerIfNotLast, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFirstOrgForUser = `-- name: GetFirstOrgForUser :one
SELECT m.org_id
  FROM org_members m
 WHERE m.user_id = $1
 ORDER BY m.created_at ASC, m.org_id ASC
 LIMIT 1
`

func (q *Queries) GetFirstOrgForUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstOrgForUser, userID)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, is_super_admin, created_at, updated_at, session_epoch FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionEpoch,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, is_super_admin, created_at, updated_at, session_epoch FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionEpoch,
	)
	return i, err
}

const listOrgMembersByOrg = `-- name: ListOrgMembersByOrg :many
SELECT m.org_id, m.user_id, m.role, m.created_at,
       u.email, u.name
  FROM org_members m
  JOIN users u ON u.id = m.user_id
 WHERE m.org_id = $1
 ORDER BY m.created_at ASC
`

type ListOrgMembersByOrgRow struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
	Name      *string            `json:"name"`
}

func (q *Queries) ListOrgMembersByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersByOrgRow{}
	for rows.Next() {
		var i ListOrgMembersByOrgRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, m.role
  FROM organizations o
  JOIN org_members m ON m.org_id = o.id
 WHERE m.user_id = $1
 ORDER BY m.created_at ASC, o.id ASC
`

type ListOrgsForUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListOrgsForUser(ctx context.Context, userID pgtype.UUID) ([]ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgsForUserRow{}
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUserToSuperAdmin = `-- name: PromoteUserToSuperAdmin :exec
UPDATE users SET is_super_admin = TRUE, updated_at = now() WHERE email = $1
`

func (q *Queries) PromoteUserToSuperAdmin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, promoteUserToSuperAdmin, email)
	return err
}

const transferOrgOwnership = `-- name: TransferOrgOwnership :execrows
UPDATE org_members m
   SET role = CASE
     WHEN m.user_id = $1 THEN 'owner'
     WHEN m.role   = 'owner' AND m.user_id = $2 THEN 'admin'
     ELSE m.role
   END
 WHERE m.org_id = $3
   AND EXISTS (
     SELECT 1 FROM org_members om
      WHERE om.org_id = $3 AND om.user_id = $2 AND om.role = 'owner'
   )
   AND EXISTS (
     SELECT 1 FROM org_members om
      WHERE om.org_id = $3 AND om.user_id = $1
   )
`

type TransferOrgOwnershipParams struct {
	ToUserID     pgtype.UUID `json:"to_user_id"`
	CallerUserID pgtype.UUID `json:"caller_user_id"`
	OrgID        pgtype.UUID `json:"org_id"`
}

// Atomic transfer: promote $2 to owner, demote the CURRENT owner (which
// must be the caller, $3) to admin. The two EXISTS guards make the whole
// thing self-cancelling under races — if the caller has been demoted by a
// concurrent op, or the target has been removed, the UPDATE matches 0
// rows and the handler returns 403/400. No SELECT-then-UPDATE TOCTOU.
func (q *Queries) TransferOrgOwnership(ctx context.Context, arg TransferOrgOwnershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferOrgOwnership, arg.ToUserID, arg.CallerUserID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :exec
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const updateOrgName = `-- name: UpdateOrgName :one
UPDATE organizations
   SET name = $2, updated_at = now()
 WHERE id = $1
 RETURNING id, name, slug, created_at, updated_at
`

type UpdateOrgNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrgName, arg.ID, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
