// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (email, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, token_hash, expires_at, used_at, created_at
`

type CreateMagicLinkTokenParams struct {
	Email     string             `json:"email"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken, arg.Email, arg.TokenHash, arg.ExpiresAt)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMagicLinkToken = `-- name: GetActiveMagicLinkToken :one
SELECT id, email, token_hash, expires_at, used_at, created_at FROM magic_link_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

// FOR UPDATE locks the row for the consume transaction so two concurrent
// verifies can't both see it active: the second blocks, then re-checks the
// WHERE after the first commits used_at and finds no row (single-use enforced).
func (q *Queries) GetActiveMagicLinkToken(ctx context.Context, tokenHash []byte) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, getActiveMagicLinkToken, tokenHash)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_link_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMagicLinkUsed, id)
	return err
}
