// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_delivery_attempts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageDeliveryAttempt = `-- name: CreateMessageDeliveryAttempt :one
INSERT INTO message_delivery_attempts
  (delivery_id, attempt_num, response_status, response_headers, response_body, duration_ms, error_message, attempted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, delivery_id, attempt_num, response_status, response_headers, response_body, duration_ms, error_message, attempted_at
`

type CreateMessageDeliveryAttemptParams struct {
	DeliveryID      pgtype.UUID `json:"delivery_id"`
	AttemptNum      int32       `json:"attempt_num"`
	ResponseStatus  *int32      `json:"response_status"`
	ResponseHeaders []byte      `json:"response_headers"`
	ResponseBody    []byte      `json:"response_body"`
	DurationMs      *int32      `json:"duration_ms"`
	ErrorMessage    *string     `json:"error_message"`
}

func (q *Queries) CreateMessageDeliveryAttempt(ctx context.Context, arg CreateMessageDeliveryAttemptParams) (MessageDeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createMessageDeliveryAttempt,
		arg.DeliveryID,
		arg.AttemptNum,
		arg.ResponseStatus,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.DurationMs,
		arg.ErrorMessage,
	)
	var i MessageDeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.AttemptNum,
		&i.ResponseStatus,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.AttemptedAt,
	)
	return i, err
}

const listAttemptsByEndpoint = `-- name: ListAttemptsByEndpoint :many
SELECT a.id, a.delivery_id, a.attempt_num, a.response_status, a.response_headers, a.response_body, a.duration_ms, a.error_message, a.attempted_at FROM message_delivery_attempts a
  JOIN message_deliveries d ON d.id = a.delivery_id
 WHERE d.endpoint_id = $1
 ORDER BY a.attempted_at DESC LIMIT $2
`

type ListAttemptsByEndpointParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListAttemptsByEndpoint(ctx context.Context, arg ListAttemptsByEndpointParams) ([]MessageDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByEndpoint, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageDeliveryAttempt{}
	for rows.Next() {
		var i MessageDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.AttemptNum,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByMessage = `-- name: ListAttemptsByMessage :many
SELECT a.id, a.delivery_id, a.attempt_num, a.response_status, a.response_headers, a.response_body, a.duration_ms, a.error_message, a.attempted_at FROM message_delivery_attempts a
  JOIN message_deliveries d ON d.id = a.delivery_id
 WHERE d.message_id = $1
 ORDER BY a.attempted_at DESC
`

func (q *Queries) ListAttemptsByMessage(ctx context.Context, messageID pgtype.UUID) ([]MessageDeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageDeliveryAttempt{}
	for rows.Next() {
		var i MessageDeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.AttemptNum,
			&i.ResponseStatus,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
