// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (app_id, org_id, event_type, payload, payload_hash, event_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (app_id, event_id) WHERE event_id IS NOT NULL DO NOTHING
RETURNING id, app_id, org_id, event_type, payload, payload_hash, event_id, created_at
`

type CreateMessageParams struct {
	AppID       pgtype.UUID `json:"app_id"`
	OrgID       pgtype.UUID `json:"org_id"`
	EventType   string      `json:"event_type"`
	Payload     []byte      `json:"payload"`
	PayloadHash string      `json:"payload_hash"`
	EventID     *string     `json:"event_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.AppID,
		arg.OrgID,
		arg.EventType,
		arg.Payload,
		arg.PayloadHash,
		arg.EventID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByAppEventID = `-- name: GetMessageByAppEventID :one
SELECT id, app_id, org_id, event_type, payload, payload_hash, event_id, created_at FROM messages WHERE app_id = $1 AND event_id = $2
`

type GetMessageByAppEventIDParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	EventID *string     `json:"event_id"`
}

func (q *Queries) GetMessageByAppEventID(ctx context.Context, arg GetMessageByAppEventIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByAppEventID, arg.AppID, arg.EventID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageForApp = `-- name: GetMessageForApp :one
SELECT id, app_id, org_id, event_type, payload, payload_hash, event_id, created_at FROM messages WHERE id = $1 AND app_id = $2
`

type GetMessageForAppParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetMessageForApp(ctx context.Context, arg GetMessageForAppParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageForApp, arg.ID, arg.AppID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.OrgID,
		&i.EventType,
		&i.Payload,
		&i.PayloadHash,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByApp = `-- name: ListMessagesByApp :many
SELECT id, app_id, org_id, event_type, payload_hash, event_id, created_at
  FROM messages WHERE app_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListMessagesByAppParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Limit int32       `json:"limit"`
}

type ListMessagesByAppRow struct {
	ID          pgtype.UUID        `json:"id"`
	AppID       pgtype.UUID        `json:"app_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	EventType   string             `json:"event_type"`
	PayloadHash string             `json:"payload_hash"`
	EventID     *string            `json:"event_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessagesByApp(ctx context.Context, arg ListMessagesByAppParams) ([]ListMessagesByAppRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByApp, arg.AppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByAppRow{}
	for rows.Next() {
		var i ListMessagesByAppRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.OrgID,
			&i.EventType,
			&i.PayloadHash,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
