// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByStatePerConnection = `-- name: CountEventsByStatePerConnection :many
SELECT connection_id, status, count(*) AS n
FROM events
WHERE status IN ('queued', 'failed', 'paused')
GROUP BY connection_id, status
`

type CountEventsByStatePerConnectionRow struct {
	ConnectionID pgtype.UUID `json:"connection_id"`
	Status       string      `json:"status"`
	N            int64       `json:"n"`
}

func (q *Queries) CountEventsByStatePerConnection(ctx context.Context) ([]CountEventsByStatePerConnectionRow, error) {
	rows, err := q.db.Query(ctx, countEventsByStatePerConnection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByStatePerConnectionRow{}
	for rows.Next() {
		var i CountEventsByStatePerConnectionRow
		if err := rows.Scan(&i.ConnectionID, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionInfo = `-- name: ListConnectionInfo :many
SELECT id, name FROM connections
`

type ListConnectionInfoRow struct {
	ID   pgtype.UUID `json:"id"`
	Name *string     `json:"name"`
}

func (q *Queries) ListConnectionInfo(ctx context.Context) ([]ListConnectionInfoRow, error) {
	rows, err := q.db.Query(ctx, listConnectionInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionInfoRow{}
	for rows.Next() {
		var i ListConnectionInfoRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinationInfo = `-- name: ListDestinationInfo :many
SELECT id, name FROM destinations
`

type ListDestinationInfoRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListDestinationInfo(ctx context.Context) ([]ListDestinationInfoRow, error) {
	rows, err := q.db.Query(ctx, listDestinationInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDestinationInfoRow{}
	for rows.Next() {
		var i ListDestinationInfoRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceInfo = `-- name: ListSourceInfo :many
SELECT id, name FROM sources
`

type ListSourceInfoRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListSourceInfo(ctx context.Context) ([]ListSourceInfoRow, error) {
	rows, err := q.db.Query(ctx, listSourceInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceInfoRow{}
	for rows.Next() {
		var i ListSourceInfoRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
