// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	KeyHash    []byte             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Attempt struct {
	ID              pgtype.UUID        `json:"id"`
	EventID         pgtype.UUID        `json:"event_id"`
	AttemptNum      int32              `json:"attempt_num"`
	ResponseStatus  *int32             `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	DurationMs      *int32             `json:"duration_ms"`
	QueuedInMs      *int32             `json:"queued_in_ms"`
	ErrorMessage    *string            `json:"error_message"`
	AttemptedAt     pgtype.Timestamptz `json:"attempted_at"`
}

type AuditLog struct {
	ID                 int64              `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	ActorUserID        pgtype.UUID        `json:"actor_user_id"`
	ActorApiKeyID      pgtype.UUID        `json:"actor_api_key_id"`
	ActorEmailSnapshot *string            `json:"actor_email_snapshot"`
	Action             string             `json:"action"`
	TargetType         string             `json:"target_type"`
	TargetID           pgtype.UUID        `json:"target_id"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type CliSession struct {
	ID         pgtype.UUID        `json:"id"`
	SourceID   pgtype.UUID        `json:"source_id"`
	TokenHash  []byte             `json:"token_hash"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Connection struct {
	ID                  pgtype.UUID        `json:"id"`
	SourceID            pgtype.UUID        `json:"source_id"`
	DestinationID       pgtype.UUID        `json:"destination_id"`
	Enabled             bool               `json:"enabled"`
	MaxRetries          int32              `json:"max_retries"`
	RetryStrategy       string             `json:"retry_strategy"`
	RetryBaseMs         int32              `json:"retry_base_ms"`
	RetryCapMs          int32              `json:"retry_cap_ms"`
	RetryJitterPct      int32              `json:"retry_jitter_pct"`
	CustomRetrySchedule []byte             `json:"custom_retry_schedule"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Destination struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Url            *string            `json:"url"`
	AuthConfig     []byte             `json:"auth_config"`
	RateLimitRps   *int32             `json:"rate_limit_rps"`
	RateLimitBurst *int32             `json:"rate_limit_burst"`
	MaxInflight    *int32             `json:"max_inflight"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID            pgtype.UUID        `json:"id"`
	RequestID     pgtype.UUID        `json:"request_id"`
	ConnectionID  pgtype.UUID        `json:"connection_id"`
	Status        string             `json:"status"`
	AttemptCount  int32              `json:"attempt_count"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MagicLinkToken struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrgInvite struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	TokenHash  []byte             `json:"token_hash"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OrgMember struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Request struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	HTTPMethod  string             `json:"http_method"`
	HTTPPath    string             `json:"http_path"`
	Headers     []byte             `json:"headers"`
	BodyHash    string             `json:"body_hash"`
	BodyRef     string             `json:"body_ref"`
	BodySize    int32              `json:"body_size"`
	ContentType *string            `json:"content_type"`
	SigVerified bool               `json:"sig_verified"`
	IngestIP    *netip.Addr        `json:"ingest_ip"`
	ReceivedAt  pgtype.Timestamptz `json:"received_at"`
}

type RequestBody struct {
	RequestID pgtype.UUID        `json:"request_id"`
	Body      []byte             `json:"body"`
	StoredAt  pgtype.Timestamptz `json:"stored_at"`
}

type Source struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	IngestToken   string             `json:"ingest_token"`
	SigningConfig []byte             `json:"signing_config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         *string            `json:"name"`
	IsSuperAdmin bool               `json:"is_super_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
