// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_invites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrgInvite = `-- name: CreateOrgInvite :one
INSERT INTO org_invites (org_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateOrgInviteParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	TokenHash []byte             `json:"token_hash"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrgInvite(ctx context.Context, arg CreateOrgInviteParams) (OrgInvite, error) {
	row := q.db.QueryRow(ctx, createOrgInvite,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrgInvite = `-- name: DeleteOrgInvite :exec
DELETE FROM org_invites WHERE id = $1 AND org_id = $2
`

type DeleteOrgInviteParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteOrgInvite(ctx context.Context, arg DeleteOrgInviteParams) error {
	_, err := q.db.Exec(ctx, deleteOrgInvite, arg.ID, arg.OrgID)
	return err
}

const getActiveOrgInviteByTokenHash = `-- name: GetActiveOrgInviteByTokenHash :one
SELECT i.id, i.org_id, i.email, i.role, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.created_at, o.name AS org_name
  FROM org_invites i
  JOIN organizations o ON o.id = i.org_id
 WHERE i.token_hash = $1
   AND i.accepted_at IS NULL
   AND i.expires_at > now()
`

type GetActiveOrgInviteByTokenHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	TokenHash  []byte             `json:"token_hash"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	OrgName    string             `json:"org_name"`
}

func (q *Queries) GetActiveOrgInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveOrgInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveOrgInviteByTokenHash, tokenHash)
	var i GetActiveOrgInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.OrgName,
	)
	return i, err
}

const listOrgInvitesByOrg = `-- name: ListOrgInvitesByOrg :many
SELECT i.id,
       i.org_id,
       i.email,
       i.role,
       i.expires_at,
       i.accepted_at,
       i.created_at,
       u.email AS invited_by_email
  FROM org_invites i
  JOIN users u ON u.id = i.invited_by
 WHERE i.org_id = $1
 ORDER BY i.created_at DESC
`

type ListOrgInvitesByOrgRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	InvitedByEmail string             `json:"invited_by_email"`
}

// Explicit column list (no SELECT i.*) — token_hash is a secret-adjacent
// value (sha256 of the bearer token) and must never leave the database.
// invited_by UUID is omitted; we surface invited_by_email for the UI.
func (q *Queries) ListOrgInvitesByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListOrgInvitesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listOrgInvitesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgInvitesByOrgRow{}
	for rows.Next() {
		var i ListOrgInvitesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.InvitedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrgInvitesByEmail = `-- name: ListPendingOrgInvitesByEmail :many
SELECT id, org_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM org_invites
 WHERE email = $1
   AND accepted_at IS NULL
   AND expires_at > now()
`

func (q *Queries) ListPendingOrgInvitesByEmail(ctx context.Context, email string) ([]OrgInvite, error) {
	rows, err := q.db.Query(ctx, listPendingOrgInvitesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgInvite{}
	for rows.Next() {
		var i OrgInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrgInviteAccepted = `-- name: MarkOrgInviteAccepted :exec
UPDATE org_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkOrgInviteAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOrgInviteAccepted, id)
	return err
}
