// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs_projects_users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO NOTHING
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug) VALUES ($1, $2) RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (org_id, name, slug) VALUES ($1, $2, $3) RETURNING id, org_id, name, slug, created_at, updated_at
`

type CreateProjectParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
	Slug  string      `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrgID, arg.Name, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id, email, name, is_super_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email string  `json:"email"`
	Name  *string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByOrgAndSlug = `-- name: GetProjectByOrgAndSlug :one
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE org_id = $1 AND slug = $2
`

type GetProjectByOrgAndSlugParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Slug  string      `json:"slug"`
}

func (q *Queries) GetProjectByOrgAndSlug(ctx context.Context, arg GetProjectByOrgAndSlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOrgAndSlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, is_super_admin, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, is_super_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT u.id, u.email, u.name, u.is_super_admin, u.created_at, u.updated_at FROM users u
JOIN org_members m ON m.user_id = u.id
WHERE m.org_id = $1
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsSuperAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, name, slug, created_at, updated_at FROM projects WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUserToSuperAdmin = `-- name: PromoteUserToSuperAdmin :exec
UPDATE users SET is_super_admin = TRUE, updated_at = now() WHERE email = $1
`

func (q *Queries) PromoteUserToSuperAdmin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, promoteUserToSuperAdmin, email)
	return err
}
