// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	// Cross-tenant event throughput for the super-admin overview (count since @since).
	AdminEventsSince(ctx context.Context, since pgtype.Timestamptz) (int64, error)
	// Cross-tenant top sources by event volume since @since (source reached via the
	// originating request), for the super-admin overview.
	AdminTopSources(ctx context.Context, since pgtype.Timestamptz) ([]AdminTopSourcesRow, error)
	// Invalidate all of a user's outstanding signed session cookies by advancing
	// their epoch. Used by logout (logout-all) and future disable/security flows.
	BumpUserSessionEpoch(ctx context.Context, id pgtype.UUID) error
	// Reaper: atomically re-queue events that never entered the dqueue or lost their
	// owner, and are therefore genuinely stuck. Two cases:
	//   * 'queued' older than @stuck_before — the ingest Enqueue failed, so the event
	//     was never put on the dqueue.
	//   * 'in_flight' on a CLI destination — the CLI dispatch path Acks the leased
	//     member at handoff to the WS tunnel, so if the tunnel died mid-flight nothing
	//     owns the event any more.
	// HTTP 'in_flight' events are deliberately excluded: the dqueue recoverer (the
	// dq:processing lease) plus the scheduled ZSET own their retry backoff AND their
	// worker-death recovery, so reaping them would double-deliver and bypass the
	// backoff schedule. @stuck_before must exceed the delivery + CLI response
	// timeouts. FOR UPDATE OF e SKIP LOCKED lets replicas run concurrently without
	// double-claiming (and locks only events, not the joined rows).
	// ponytail: a pathologically low rate limit (refill > @stuck_before) could let
	// a rate-limit-deferred 'queued' event be reaped early → one duplicate delivery;
	// acceptable under the system's at-least-once contract.
	ClaimStuckEvents(ctx context.Context, arg ClaimStuckEventsParams) ([]ClaimStuckEventsRow, error)
	// Per-status event counts for one connection over a recent window, excluding
	// synthetic test events so health metrics reflect real traffic. Caller passes
	// the window start; folds the rows into delivered/failed/pending buckets.
	CountEventsByConnectionSince(ctx context.Context, arg CountEventsByConnectionSinceParams) ([]CountEventsByConnectionSinceRow, error)
	// Per-connection, per-status counts for a whole org over a recent window,
	// excluding test events. One query feeds the connections-list stat column
	// (avoids an N+1 of CountEventsByConnectionSince). Handler folds by
	// connection_id into delivered/failed/pending buckets.
	CountEventsByOrgGroupedByConnection(ctx context.Context, arg CountEventsByOrgGroupedByConnectionParams) ([]CountEventsByOrgGroupedByConnectionRow, error)
	CountEventsByStatePerConnection(ctx context.Context) ([]CountEventsByStatePerConnectionRow, error)
	CountOrgMembershipsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error)
	// Fan-out insert: one queued event per connection_id, all sharing the same
	// request_id and org_id (a source belongs to exactly one org). One statement
	// instead of a roundtrip per destination. RETURNING order is not guaranteed,
	// so callers key the returned rows by connection_id rather than positional
	// index. @is_test is a per-request scalar (a request is wholly test or not).
	CreateEventsBatch(ctx context.Context, arg CreateEventsBatchParams) ([]Event, error)
	CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error)
	CreateOrgInvite(ctx context.Context, arg CreateOrgInviteParams) (OrgInvite, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConnectionForOrg(ctx context.Context, arg DeleteConnectionForOrgParams) error
	DeleteDestinationForOrg(ctx context.Context, arg DeleteDestinationForOrgParams) error
	// Reclaim spent + lapsed tokens: expires_at is set at creation, so both used
	// and never-used tokens become deletable once their expiry is older than
	// @cutoff. Backed by magic_link_tokens_expires_idx.
	DeleteExpiredMagicLinkTokens(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// Reclaim invites whose expiry passed before @cutoff (accepted or not — an
	// accepted invite is consumed, a lapsed one is dead). Backed by
	// org_invites_expires_idx.
	DeleteExpiredOrgInvites(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	DeleteOrgInvite(ctx context.Context, arg DeleteOrgInviteParams) error
	DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error
	// Atomic remove: delete the owner row ONLY IF at least one other owner
	// remains. Same race-free invariant as DemoteOrgOwnerIfNotLast.
	DeleteOrgOwnerIfNotLast(ctx context.Context, arg DeleteOrgOwnerIfNotLastParams) (int64, error)
	DeleteOrganization(ctx context.Context, id pgtype.UUID) error
	DeleteSourceForOrg(ctx context.Context, arg DeleteSourceForOrgParams) (string, error)
	// Atomic demote: change role to $3 ONLY IF at least one other owner
	// remains. The whole operation is one statement, so two concurrent
	// demote requests can't both pass a count-then-update race.
	DemoteOrgOwnerIfNotLast(ctx context.Context, arg DemoteOrgOwnerIfNotLastParams) (int64, error)
	// Gap-filled delivery outcomes over time for ONE destination. Events reach a
	// destination through their connection, so join connections to filter. Same
	// generate_series gap-fill + UTC buckets as EventsHistogram; empty buckets come
	// back as a NULL-status row with count 0.
	DestinationDeliveryHistogram(ctx context.Context, arg DestinationDeliveryHistogramParams) ([]DestinationDeliveryHistogramRow, error)
	// Window totals for the delivery-rate + avg-latency cards. delivered/total gives
	// the rate; avg_latency_ms averages the delivery HTTP call time recorded per
	// attempt (NULL when no completed attempts in the window).
	DestinationDeliveryStats(ctx context.Context, arg DestinationDeliveryStatsParams) (DestinationDeliveryStatsRow, error)
	// Time-bucketed event counts by status for the events-page timeline graph.
	// @bucket is a date_trunc unit ('minute' | 'hour' | 'day' | 'week') chosen by
	// the handler from the selected range. The series is GAP-FILLED in SQL:
	// generate_series emits every bucket from date_trunc(@after) through now(), so
	// quiet buckets come back as one row with a NULL status and count 0 — the client
	// plots the rows as-is, no reconstruction. Buckets are UTC-aligned. Same optional
	// connection_id/status filters as ListEvents; includes test events.
	EventsHistogram(ctx context.Context, arg EventsHistogramParams) ([]EventsHistogramRow, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	// FOR UPDATE locks the row for the consume transaction so two concurrent
	// verifies can't both see it active: the second blocks, then re-checks the
	// WHERE after the first commits used_at and finds no row (single-use enforced).
	GetActiveMagicLinkToken(ctx context.Context, tokenHash []byte) (MagicLinkToken, error)
	GetActiveOrgInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveOrgInviteByTokenHashRow, error)
	GetConnectionByID(ctx context.Context, id pgtype.UUID) (Connection, error)
	GetConnectionForOrg(ctx context.Context, arg GetConnectionForOrgParams) (Connection, error)
	GetDestinationForOrg(ctx context.Context, arg GetDestinationForOrgParams) (Destination, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	// Full event view for the detail page: the event, its connection's
	// source/destination, the destination endpoint, and the originating request
	// (method/path/headers/body pointer). One org-scoped row that backs the
	// Overview + Request-data panels.
	GetEventDetailForOrg(ctx context.Context, arg GetEventDetailForOrgParams) (GetEventDetailForOrgRow, error)
	GetEventForDelivery(ctx context.Context, id pgtype.UUID) (GetEventForDeliveryRow, error)
	// org_id lives on events now, so this is a direct two-column lookup (PK + org)
	// instead of a join through connections/sources.
	GetEventForOrg(ctx context.Context, arg GetEventForOrgParams) (Event, error)
	GetFirstOrgForUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetRequestBody(ctx context.Context, requestID pgtype.UUID) ([]byte, error)
	GetSourceByIngestToken(ctx context.Context, ingestToken string) (Source, error)
	GetSourceForOrg(ctx context.Context, arg GetSourceForOrgParams) (Source, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Cross-tenant (super-admin console): destinations with delivery failures in the
	// last 24h, worst first. total/failed let the handler compute a failure rate.
	// Only destinations that actually failed are returned (HAVING).
	HotDestinations(ctx context.Context) ([]HotDestinationsRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertRequestBody(ctx context.Context, arg InsertRequestBodyParams) error
	ListAPIKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ApiKey, error)
	ListAllOrganizations(ctx context.Context) ([]Organization, error)
	ListAttemptsByEvent(ctx context.Context, eventID pgtype.UUID) ([]Attempt, error)
	// LEFT JOIN may yield NULL for u/k columns; COALESCE so sqlc generates
	// non-nullable string fields (sqlc + LEFT JOIN nullability is awkward).
	ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]ListAuditLogsByOrgRow, error)
	ListConnectionInfo(ctx context.Context) ([]ListConnectionInfoRow, error)
	ListConnectionsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Connection, error)
	ListDestinationInfo(ctx context.Context) ([]ListDestinationInfoRow, error)
	ListDestinationsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Destination, error)
	ListEnabledConnectionsBySource(ctx context.Context, sourceID pgtype.UUID) ([]Connection, error)
	// Keyset pagination on (created_at DESC, id DESC). Optional connection_id and
	// status filters use the narg NULL-guard idiom (see audit_logs.sql): a nil
	// param drops the clause. The handler passes connection_id as a Valid pgtype
	// whenever the query param is present (even an all-zero UUID), so a present
	// filter that matches nothing returns empty rather than falling through to
	// unfiltered. events_connection_created_idx serves the connection+order path;
	// events_org_created_idx the org-only path.
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	// Explicit column list (no SELECT i.*) — token_hash is a secret-adjacent
	// value (sha256 of the bearer token) and must never leave the database.
	// invited_by UUID is omitted; we surface invited_by_email for the UI.
	ListOrgInvitesByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListOrgInvitesByOrgRow, error)
	ListOrgMembersByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersByOrgRow, error)
	ListOrgsForUser(ctx context.Context, userID pgtype.UUID) ([]ListOrgsForUserRow, error)
	ListPendingOrgInvitesByEmail(ctx context.Context, email string) ([]OrgInvite, error)
	ListSourceInfo(ctx context.Context) ([]ListSourceInfoRow, error)
	ListSourcesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Source, error)
	// attempt_count is bumped once per delivery cycle by MarkEventInFlight; the
	// terminal transitions must NOT increment again (that double-counted attempts
	// and made recorded attempt_num values skip).
	MarkEventDelivered(ctx context.Context, id pgtype.UUID) error
	// Terminal state for a CLI event that waited past the tunnel deadline with no
	// live listener. Unlike 'failed' it never got a delivery attempt; it's dropped
	// until a user manually retries (ResetEventForManualRetry re-queues it).
	MarkEventDiscarded(ctx context.Context, id pgtype.UUID) error
	MarkEventFailed(ctx context.Context, id pgtype.UUID) error
	// The single attempt_count incrementer. recordAttempt derives attempt_num from
	// the pre-increment count, so this keeps attempt_num monotonic and gap-free.
	MarkEventInFlight(ctx context.Context, id pgtype.UUID) error
	MarkMagicLinkUsed(ctx context.Context, id pgtype.UUID) error
	MarkOrgInviteAccepted(ctx context.Context, id pgtype.UUID) error
	// COALESCE pattern so unspecified fields keep current values.
	// Tenancy is enforced by joining through sources.org_id.
	PatchConnectionForOrg(ctx context.Context, arg PatchConnectionForOrgParams) (Connection, error)
	// COALESCE pattern so unspecified fields keep current values.
	PatchDestinationForOrg(ctx context.Context, arg PatchDestinationForOrgParams) (Destination, error)
	PromoteUserToSuperAdmin(ctx context.Context, email string) error
	// Do NOT reset attempt_count: zeroing it made the next attempt reuse
	// attempt_num=1, colliding with the original attempt on UNIQUE(event_id,
	// attempt_num) and silently dropping the retry's attempt row. Keep it monotonic;
	// the fair-queue retry counter resets separately by re-enqueuing with Attempt=0.
	ResetEventForManualRetry(ctx context.Context, id pgtype.UUID) error
	ResetEventForRetry(ctx context.Context, arg ResetEventForRetryParams) error
	RevokeAPIKeyForOrg(ctx context.Context, arg RevokeAPIKeyForOrgParams) error
	// Gap-filled ingest-request volume over time for ONE source (single series, no
	// status dimension). Same gap-fill contract as the delivery histogram.
	SourceRequestHistogram(ctx context.Context, arg SourceRequestHistogramParams) ([]SourceRequestHistogramRow, error)
	// Window totals for the requests-rate + avg-events-per-request (fan-out) cards.
	SourceRequestStats(ctx context.Context, arg SourceRequestStatsParams) (SourceRequestStatsRow, error)
	// Debounced: skip the write (and the WAL row / heap update / index churn)
	// when the key was already touched within the past minute. Authenticated
	// API traffic can exceed 1 req/s per key; without this gate the api_keys
	// table is a write hotspot on the hot path. last_used_at accuracy at
	// 1-minute granularity is the trade-off — good enough for "when did this
	// key last work?" answer in the UI.
	TouchAPIKey(ctx context.Context, id pgtype.UUID) error
	// Atomic transfer: promote $2 to owner, demote the CURRENT owner (which
	// must be the caller, $3) to admin. The two EXISTS guards make the whole
	// thing self-cancelling under races — if the caller has been demoted by a
	// concurrent op, or the target has been removed, the UPDATE matches 0
	// rows and the handler returns 403/400. No SELECT-then-UPDATE TOCTOU.
	TransferOrgOwnership(ctx context.Context, arg TransferOrgOwnershipParams) (int64, error)
	UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error
	UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) (Organization, error)
	UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error)
}

var _ Querier = (*Queries)(nil)
