// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_bodies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireOldRequestBodies = `-- name: ExpireOldRequestBodies :execrows
UPDATE request_bodies SET body = NULL
 WHERE stored_at < $1 AND body IS NOT NULL
   AND request_id NOT IN (SELECT request_id FROM bookmarks)
`

func (q *Queries) ExpireOldRequestBodies(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldRequestBodies, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequestBody = `-- name: GetRequestBody :one
SELECT body FROM request_bodies WHERE request_id = $1 AND body IS NOT NULL
`

// Excludes a retention-expunged (NULL) body so it surfaces as ErrNoRows, taking
// the delivery worker's missing-body terminate path instead of sending empty.
func (q *Queries) GetRequestBody(ctx context.Context, requestID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRequestBody, requestID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const insertRequestBody = `-- name: InsertRequestBody :exec
INSERT INTO request_bodies (request_id, body) VALUES ($1, $2)
`

type InsertRequestBodyParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	Body      []byte      `json:"body"`
}

func (q *Queries) InsertRequestBody(ctx context.Context, arg InsertRequestBodyParams) error {
	_, err := q.db.Exec(ctx, insertRequestBody, arg.RequestID, arg.Body)
	return err
}
