// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    id, source_id, http_method, http_path, headers, body_hash, body_ref,
    body_size, content_type, sig_verified, ingest_ip
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, source_id, http_method, http_path, headers, body_hash, body_ref, body_size, content_type, sig_verified, ingest_ip, received_at
`

type CreateRequestParams struct {
	ID          pgtype.UUID `json:"id"`
	SourceID    pgtype.UUID `json:"source_id"`
	HTTPMethod  string      `json:"http_method"`
	HTTPPath    string      `json:"http_path"`
	Headers     []byte      `json:"headers"`
	BodyHash    string      `json:"body_hash"`
	BodyRef     string      `json:"body_ref"`
	BodySize    int32       `json:"body_size"`
	ContentType *string     `json:"content_type"`
	SigVerified bool        `json:"sig_verified"`
	IngestIP    *netip.Addr `json:"ingest_ip"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ID,
		arg.SourceID,
		arg.HTTPMethod,
		arg.HTTPPath,
		arg.Headers,
		arg.BodyHash,
		arg.BodyRef,
		arg.BodySize,
		arg.ContentType,
		arg.SigVerified,
		arg.IngestIP,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.HTTPMethod,
		&i.HTTPPath,
		&i.Headers,
		&i.BodyHash,
		&i.BodyRef,
		&i.BodySize,
		&i.ContentType,
		&i.SigVerified,
		&i.IngestIP,
		&i.ReceivedAt,
	)
	return i, err
}

const getRequestForReplay = `-- name: GetRequestForReplay :one
SELECT r.id, r.source_id, r.http_method, r.http_path, r.headers, r.body_ref,
       r.content_type, r.body_size
FROM requests r
JOIN sources s ON s.id = r.source_id
WHERE r.id = $1 AND s.org_id = $2
`

type GetRequestForReplayParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

type GetRequestForReplayRow struct {
	ID          pgtype.UUID `json:"id"`
	SourceID    pgtype.UUID `json:"source_id"`
	HTTPMethod  string      `json:"http_method"`
	HTTPPath    string      `json:"http_path"`
	Headers     []byte      `json:"headers"`
	BodyRef     string      `json:"body_ref"`
	ContentType *string     `json:"content_type"`
	BodySize    int32       `json:"body_size"`
}

func (q *Queries) GetRequestForReplay(ctx context.Context, arg GetRequestForReplayParams) (GetRequestForReplayRow, error) {
	row := q.db.QueryRow(ctx, getRequestForReplay, arg.ID, arg.OrgID)
	var i GetRequestForReplayRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.HTTPMethod,
		&i.HTTPPath,
		&i.Headers,
		&i.BodyRef,
		&i.ContentType,
		&i.BodySize,
	)
	return i, err
}
