// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_bodies.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestBody = `-- name: GetRequestBody :one
SELECT body FROM request_bodies WHERE request_id = $1
`

func (q *Queries) GetRequestBody(ctx context.Context, requestID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRequestBody, requestID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const insertRequestBody = `-- name: InsertRequestBody :exec
INSERT INTO request_bodies (request_id, body) VALUES ($1, $2)
`

type InsertRequestBodyParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	Body      []byte      `json:"body"`
}

func (q *Queries) InsertRequestBody(ctx context.Context, arg InsertRequestBodyParams) error {
	_, err := q.db.Exec(ctx, insertRequestBody, arg.RequestID, arg.Body)
	return err
}
