// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenarios.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO scenarios (org_id, name, description) VALUES ($1, $2, $3) RETURNING id, org_id, name, description, created_at, updated_at
`

type CreateScenarioParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, createScenario, arg.OrgID, arg.Name, arg.Description)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScenarioForOrg = `-- name: DeleteScenarioForOrg :execrows
DELETE FROM scenarios WHERE id = $1 AND org_id = $2
`

type DeleteScenarioForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteScenarioForOrg(ctx context.Context, arg DeleteScenarioForOrgParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScenarioForOrg, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScenarioSteps = `-- name: DeleteScenarioSteps :exec
DELETE FROM scenario_steps WHERE scenario_id = $1
`

func (q *Queries) DeleteScenarioSteps(ctx context.Context, scenarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScenarioSteps, scenarioID)
	return err
}

const getScenarioForOrg = `-- name: GetScenarioForOrg :one
SELECT id, org_id, name, description, created_at, updated_at FROM scenarios WHERE id = $1 AND org_id = $2
`

type GetScenarioForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetScenarioForOrg(ctx context.Context, arg GetScenarioForOrgParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, getScenarioForOrg, arg.ID, arg.OrgID)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScenarioStep = `-- name: InsertScenarioStep :one
INSERT INTO scenario_steps (scenario_id, position, bookmark_id, delay_ms)
VALUES ($1, $2, $3, $4) RETURNING id, scenario_id, position, bookmark_id, delay_ms
`

type InsertScenarioStepParams struct {
	ScenarioID pgtype.UUID `json:"scenario_id"`
	Position   int32       `json:"position"`
	BookmarkID pgtype.UUID `json:"bookmark_id"`
	DelayMs    int32       `json:"delay_ms"`
}

func (q *Queries) InsertScenarioStep(ctx context.Context, arg InsertScenarioStepParams) (ScenarioStep, error) {
	row := q.db.QueryRow(ctx, insertScenarioStep,
		arg.ScenarioID,
		arg.Position,
		arg.BookmarkID,
		arg.DelayMs,
	)
	var i ScenarioStep
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Position,
		&i.BookmarkID,
		&i.DelayMs,
	)
	return i, err
}

const listScenarioSteps = `-- name: ListScenarioSteps :many
SELECT s.id, s.scenario_id, s.position, s.bookmark_id, s.delay_ms, b.name AS bookmark_name
FROM scenario_steps s JOIN bookmarks b ON b.id = s.bookmark_id
WHERE s.scenario_id = $1 ORDER BY s.position
`

type ListScenarioStepsRow struct {
	ID           pgtype.UUID `json:"id"`
	ScenarioID   pgtype.UUID `json:"scenario_id"`
	Position     int32       `json:"position"`
	BookmarkID   pgtype.UUID `json:"bookmark_id"`
	DelayMs      int32       `json:"delay_ms"`
	BookmarkName string      `json:"bookmark_name"`
}

func (q *Queries) ListScenarioSteps(ctx context.Context, scenarioID pgtype.UUID) ([]ListScenarioStepsRow, error) {
	rows, err := q.db.Query(ctx, listScenarioSteps, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScenarioStepsRow{}
	for rows.Next() {
		var i ListScenarioStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.Position,
			&i.BookmarkID,
			&i.DelayMs,
			&i.BookmarkName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenariosForOrg = `-- name: ListScenariosForOrg :many
SELECT id, org_id, name, description, created_at, updated_at FROM scenarios WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListScenariosForOrg(ctx context.Context, orgID pgtype.UUID) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenariosForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scenario{}
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScenario = `-- name: UpdateScenario :one
UPDATE scenarios SET name = $3, description = $4, updated_at = now()
WHERE id = $1 AND org_id = $2 RETURNING id, org_id, name, description, created_at, updated_at
`

type UpdateScenarioParams struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, updateScenario,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
	)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
