// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (project_id, name, type, ingest_token, signing_config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, type, ingest_token, signing_config, created_at, updated_at
`

type CreateSourceParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	IngestToken   string      `json:"ingest_token"`
	SigningConfig []byte      `json:"signing_config"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.IngestToken,
		arg.SigningConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, project_id, name, type, ingest_token, signing_config, created_at, updated_at FROM sources WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceByIngestToken = `-- name: GetSourceByIngestToken :one
SELECT id, project_id, name, type, ingest_token, signing_config, created_at, updated_at FROM sources WHERE ingest_token = $1
`

func (q *Queries) GetSourceByIngestToken(ctx context.Context, ingestToken string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByIngestToken, ingestToken)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSourcesByProject = `-- name: ListSourcesByProject :many
SELECT id, project_id, name, type, ingest_token, signing_config, created_at, updated_at FROM sources
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByProject(ctx context.Context, projectID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.IngestToken,
			&i.SigningConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
SET name = COALESCE($1, name),
    signing_config = COALESCE($2, signing_config),
    updated_at = now()
WHERE id = $3
RETURNING id, project_id, name, type, ingest_token, signing_config, created_at, updated_at
`

type UpdateSourceParams struct {
	Name          *string     `json:"name"`
	SigningConfig []byte      `json:"signing_config"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource, arg.Name, arg.SigningConfig, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
