// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (org_id, name, type, description, ingest_token, signing_config)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled, description, allowed_methods
`

type CreateSourceParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Description   string      `json:"description"`
	IngestToken   string      `json:"ingest_token"`
	SigningConfig []byte      `json:"signing_config"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.IngestToken,
		arg.SigningConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.AllowedMethods,
	)
	return i, err
}

const deleteSourceForOrg = `-- name: DeleteSourceForOrg :one
DELETE FROM sources WHERE id = $1 AND org_id = $2 RETURNING ingest_token
`

type DeleteSourceForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteSourceForOrg(ctx context.Context, arg DeleteSourceForOrgParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteSourceForOrg, arg.ID, arg.OrgID)
	var ingest_token string
	err := row.Scan(&ingest_token)
	return ingest_token, err
}

const getSourceByIngestToken = `-- name: GetSourceByIngestToken :one
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled, description, allowed_methods FROM sources WHERE ingest_token = $1 AND enabled = TRUE
`

func (q *Queries) GetSourceByIngestToken(ctx context.Context, ingestToken string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByIngestToken, ingestToken)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.AllowedMethods,
	)
	return i, err
}

const getSourceForOrg = `-- name: GetSourceForOrg :one
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled, description, allowed_methods FROM sources WHERE id = $1 AND org_id = $2
`

type GetSourceForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetSourceForOrg(ctx context.Context, arg GetSourceForOrgParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceForOrg, arg.ID, arg.OrgID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.AllowedMethods,
	)
	return i, err
}

const listSourcesByOrg = `-- name: ListSourcesByOrg :many
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled, description, allowed_methods FROM sources
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.IngestToken,
			&i.SigningConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
			&i.Description,
			&i.AllowedMethods,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources
   SET name            = COALESCE($1, name),
       description     = COALESCE($2, description),
       allowed_methods = COALESCE($3::text[], allowed_methods),
       enabled         = COALESCE($4, enabled),
       updated_at      = now()
 WHERE id = $5 AND org_id = $6
 RETURNING id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled, description, allowed_methods
`

type UpdateSourceParams struct {
	Name           *string     `json:"name"`
	Description    *string     `json:"description"`
	AllowedMethods []string    `json:"allowed_methods"`
	Enabled        *bool       `json:"enabled"`
	ID             pgtype.UUID `json:"id"`
	OrgID          pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.Name,
		arg.Description,
		arg.AllowedMethods,
		arg.Enabled,
		arg.ID,
		arg.OrgID,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.AllowedMethods,
	)
	return i, err
}
