// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (org_id, name, type, ingest_token, signing_config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled
`

type CreateSourceParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	IngestToken   string      `json:"ingest_token"`
	SigningConfig []byte      `json:"signing_config"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.IngestToken,
		arg.SigningConfig,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const deleteSourceForOrg = `-- name: DeleteSourceForOrg :exec
DELETE FROM sources WHERE id = $1 AND org_id = $2
`

type DeleteSourceForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteSourceForOrg(ctx context.Context, arg DeleteSourceForOrgParams) error {
	_, err := q.db.Exec(ctx, deleteSourceForOrg, arg.ID, arg.OrgID)
	return err
}

const getSourceByIngestToken = `-- name: GetSourceByIngestToken :one
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled FROM sources WHERE ingest_token = $1 AND enabled = TRUE
`

func (q *Queries) GetSourceByIngestToken(ctx context.Context, ingestToken string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByIngestToken, ingestToken)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const getSourceForOrg = `-- name: GetSourceForOrg :one
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled FROM sources WHERE id = $1 AND org_id = $2
`

type GetSourceForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetSourceForOrg(ctx context.Context, arg GetSourceForOrgParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceForOrg, arg.ID, arg.OrgID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}

const listSourcesByOrg = `-- name: ListSourcesByOrg :many
SELECT id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled FROM sources
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSourcesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.IngestToken,
			&i.SigningConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceEnabled = `-- name: SetSourceEnabled :one
UPDATE sources
   SET enabled = $3, updated_at = now()
 WHERE id = $1 AND org_id = $2
 RETURNING id, org_id, name, type, ingest_token, signing_config, created_at, updated_at, enabled
`

type SetSourceEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	OrgID   pgtype.UUID `json:"org_id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) SetSourceEnabled(ctx context.Context, arg SetSourceEnabledParams) (Source, error) {
	row := q.db.QueryRow(ctx, setSourceEnabled, arg.ID, arg.OrgID, arg.Enabled)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IngestToken,
		&i.SigningConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
	)
	return i, err
}
