// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgQuota = `-- name: GetOrgQuota :one
SELECT plan, quota_events_soft, quota_events_hard,
       quota_messages_soft, quota_messages_hard, quota_period
FROM organizations WHERE id = $1
`

type GetOrgQuotaRow struct {
	Plan              string `json:"plan"`
	QuotaEventsSoft   int64  `json:"quota_events_soft"`
	QuotaEventsHard   int64  `json:"quota_events_hard"`
	QuotaMessagesSoft int64  `json:"quota_messages_soft"`
	QuotaMessagesHard int64  `json:"quota_messages_hard"`
	QuotaPeriod       string `json:"quota_period"`
}

// One org's plan + limits, pinned to exactly those columns (no name/slug/
// timestamps) so GET /api/usage can't accidentally grow into a second
// `SELECT *`-shaped leak the way identity.sql:5,8 already are.
func (q *Queries) GetOrgQuota(ctx context.Context, id pgtype.UUID) (GetOrgQuotaRow, error) {
	row := q.db.QueryRow(ctx, getOrgQuota, id)
	var i GetOrgQuotaRow
	err := row.Scan(
		&i.Plan,
		&i.QuotaEventsSoft,
		&i.QuotaEventsHard,
		&i.QuotaMessagesSoft,
		&i.QuotaMessagesHard,
		&i.QuotaPeriod,
	)
	return i, err
}

const getUsageForPeriod = `-- name: GetUsageForPeriod :many
SELECT metric, count FROM usage_rollups
WHERE org_id = $1 AND period_start = $2
`

type GetUsageForPeriodParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

type GetUsageForPeriodRow struct {
	Metric string `json:"metric"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetUsageForPeriod(ctx context.Context, arg GetUsageForPeriodParams) ([]GetUsageForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getUsageForPeriod, arg.OrgID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageForPeriodRow{}
	for rows.Next() {
		var i GetUsageForPeriodRow
		if err := rows.Scan(&i.Metric, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageHistory = `-- name: GetUsageHistory :many
SELECT period_start, metric, count FROM usage_rollups
WHERE org_id = $1 AND metric = $2 AND period_start >= $3
ORDER BY period_start DESC
`

type GetUsageHistoryParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	Metric      string             `json:"metric"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

type GetUsageHistoryRow struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Metric      string             `json:"metric"`
	Count       int64              `json:"count"`
}

func (q *Queries) GetUsageHistory(ctx context.Context, arg GetUsageHistoryParams) ([]GetUsageHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUsageHistory, arg.OrgID, arg.Metric, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageHistoryRow{}
	for rows.Next() {
		var i GetUsageHistoryRow
		if err := rows.Scan(&i.PeriodStart, &i.Metric, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgQuotas = `-- name: ListOrgQuotas :many
SELECT id, name, slug, plan, quota_events_soft, quota_events_hard,
       quota_messages_soft, quota_messages_hard, quota_period
FROM organizations ORDER BY name
`

type ListOrgQuotasRow struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Slug              string      `json:"slug"`
	Plan              string      `json:"plan"`
	QuotaEventsSoft   int64       `json:"quota_events_soft"`
	QuotaEventsHard   int64       `json:"quota_events_hard"`
	QuotaMessagesSoft int64       `json:"quota_messages_soft"`
	QuotaMessagesHard int64       `json:"quota_messages_hard"`
	QuotaPeriod       string      `json:"quota_period"`
}

// Drives both reconciliation and the super-admin view.
func (q *Queries) ListOrgQuotas(ctx context.Context) ([]ListOrgQuotasRow, error) {
	rows, err := q.db.Query(ctx, listOrgQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgQuotasRow{}
	for rows.Next() {
		var i ListOrgQuotasRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.QuotaEventsSoft,
			&i.QuotaEventsHard,
			&i.QuotaMessagesSoft,
			&i.QuotaMessagesHard,
			&i.QuotaPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupAttempts = `-- name: RollupAttempts :many
SELECT org_id, period_start, sum(count)::bigint AS count FROM (
    SELECT e.org_id AS org_id,
           date_trunc($1::text, a.attempted_at)::timestamptz AS period_start,
           count(*)::bigint AS count
    FROM attempts a JOIN events e ON e.id = a.event_id
    WHERE a.attempted_at >= $2::timestamptz
    GROUP BY 1, 2
    UNION ALL
    SELECT md.org_id AS org_id,
           date_trunc($1::text, mda.attempted_at)::timestamptz AS period_start,
           count(*)::bigint AS count
    FROM message_delivery_attempts mda
    JOIN message_deliveries md ON md.id = mda.delivery_id
    WHERE mda.attempted_at >= $2::timestamptz
    GROUP BY 1, 2
) t GROUP BY 1, 2
`

type RollupAttemptsParams struct {
	Bucket string             `json:"bucket"`
	After  pgtype.Timestamptz `json:"after"`
}

type RollupAttemptsRow struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Count       int64              `json:"count"`
}

// Both delivery surfaces sum into one metric: inbound attempts are org-scoped
// through the event, outbound through message_deliveries, which carries org_id
// directly (no join to messages needed).
//
// NOTE both attempt tables use attempted_at, NOT created_at.
func (q *Queries) RollupAttempts(ctx context.Context, arg RollupAttemptsParams) ([]RollupAttemptsRow, error) {
	rows, err := q.db.Query(ctx, rollupAttempts, arg.Bucket, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupAttemptsRow{}
	for rows.Next() {
		var i RollupAttemptsRow
		if err := rows.Scan(&i.OrgID, &i.PeriodStart, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupEvents = `-- name: RollupEvents :many
SELECT org_id, date_trunc($1::text, created_at)::timestamptz AS period_start,
       count(*)::bigint AS count
FROM events
WHERE created_at >= $2::timestamptz
  AND is_test = FALSE
GROUP BY 1, 2
`

type RollupEventsParams struct {
	Bucket string             `json:"bucket"`
	After  pgtype.Timestamptz `json:"after"`
}

type RollupEventsRow struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Count       int64              `json:"count"`
}

// is_test events are excluded from the metered count. Fixture replay is the
// dev-loop feature dstream sells; throttling or billing someone for exercising
// it is the wrong default. is_test is set only by dstream's own replay and
// test-connection paths (internal/bookmark, internal/api/pipeline), never by an
// inbound webhook, so this is not a quota-evasion vector. The health-metric
// queries at db/queries/events.sql:250,262 exclude them for the same reason.
func (q *Queries) RollupEvents(ctx context.Context, arg RollupEventsParams) ([]RollupEventsRow, error) {
	rows, err := q.db.Query(ctx, rollupEvents, arg.Bucket, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupEventsRow{}
	for rows.Next() {
		var i RollupEventsRow
		if err := rows.Scan(&i.OrgID, &i.PeriodStart, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupMessages = `-- name: RollupMessages :many
SELECT org_id, date_trunc($1::text, created_at)::timestamptz AS period_start,
       count(*)::bigint AS count
FROM messages
WHERE created_at >= $2::timestamptz
GROUP BY 1, 2
`

type RollupMessagesParams struct {
	Bucket string             `json:"bucket"`
	After  pgtype.Timestamptz `json:"after"`
}

type RollupMessagesRow struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Count       int64              `json:"count"`
}

func (q *Queries) RollupMessages(ctx context.Context, arg RollupMessagesParams) ([]RollupMessagesRow, error) {
	rows, err := q.db.Query(ctx, rollupMessages, arg.Bucket, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupMessagesRow{}
	for rows.Next() {
		var i RollupMessagesRow
		if err := rows.Scan(&i.OrgID, &i.PeriodStart, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupRequests = `-- name: RollupRequests :many
SELECT s.org_id AS org_id, date_trunc($1::text, r.received_at)::timestamptz AS period_start,
       count(*)::bigint AS count
FROM requests r
JOIN sources s ON s.id = r.source_id
WHERE r.received_at >= $2::timestamptz
GROUP BY 1, 2
`

type RollupRequestsParams struct {
	Bucket string             `json:"bucket"`
	After  pgtype.Timestamptz `json:"after"`
}

type RollupRequestsRow struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Count       int64              `json:"count"`
}

// requests has no org_id and its timestamp is received_at, not created_at.
func (q *Queries) RollupRequests(ctx context.Context, arg RollupRequestsParams) ([]RollupRequestsRow, error) {
	rows, err := q.db.Query(ctx, rollupRequests, arg.Bucket, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupRequestsRow{}
	for rows.Next() {
		var i RollupRequestsRow
		if err := rows.Scan(&i.OrgID, &i.PeriodStart, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgQuota = `-- name: UpdateOrgQuota :one
UPDATE organizations
   SET plan = $2,
       quota_events_soft = $3,
       quota_events_hard = $4,
       quota_messages_soft = $5,
       quota_messages_hard = $6,
       quota_period = $7,
       updated_at = now()
 WHERE id = $1
 RETURNING plan, quota_events_soft, quota_events_hard,
           quota_messages_soft, quota_messages_hard, quota_period
`

type UpdateOrgQuotaParams struct {
	ID                pgtype.UUID `json:"id"`
	Plan              string      `json:"plan"`
	QuotaEventsSoft   int64       `json:"quota_events_soft"`
	QuotaEventsHard   int64       `json:"quota_events_hard"`
	QuotaMessagesSoft int64       `json:"quota_messages_soft"`
	QuotaMessagesHard int64       `json:"quota_messages_hard"`
	QuotaPeriod       string      `json:"quota_period"`
}

type UpdateOrgQuotaRow struct {
	Plan              string `json:"plan"`
	QuotaEventsSoft   int64  `json:"quota_events_soft"`
	QuotaEventsHard   int64  `json:"quota_events_hard"`
	QuotaMessagesSoft int64  `json:"quota_messages_soft"`
	QuotaMessagesHard int64  `json:"quota_messages_hard"`
	QuotaPeriod       string `json:"quota_period"`
}

// Sets plan + limits together (PATCH /admin/orgs/{org_id}/plan, super-admin
// only — a tenant cannot change its own quota). RETURNING is pinned the same
// way GetOrgQuota is, for the same reason.
func (q *Queries) UpdateOrgQuota(ctx context.Context, arg UpdateOrgQuotaParams) (UpdateOrgQuotaRow, error) {
	row := q.db.QueryRow(ctx, updateOrgQuota,
		arg.ID,
		arg.Plan,
		arg.QuotaEventsSoft,
		arg.QuotaEventsHard,
		arg.QuotaMessagesSoft,
		arg.QuotaMessagesHard,
		arg.QuotaPeriod,
	)
	var i UpdateOrgQuotaRow
	err := row.Scan(
		&i.Plan,
		&i.QuotaEventsSoft,
		&i.QuotaEventsHard,
		&i.QuotaMessagesSoft,
		&i.QuotaMessagesHard,
		&i.QuotaPeriod,
	)
	return i, err
}

const upsertUsageRollup = `-- name: UpsertUsageRollup :exec
INSERT INTO usage_rollups (org_id, period_start, metric, count, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (org_id, period_start, metric)
DO UPDATE SET count = EXCLUDED.count, updated_at = now()
`

type UpsertUsageRollupParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Metric      string             `json:"metric"`
	Count       int64              `json:"count"`
}

// Idempotent by (org_id, period_start, metric): the sweep re-runs the current
// period on every worker restart, so this must converge rather than add.
func (q *Queries) UpsertUsageRollup(ctx context.Context, arg UpsertUsageRollupParams) error {
	_, err := q.db.Exec(ctx, upsertUsageRollup,
		arg.OrgID,
		arg.PeriodStart,
		arg.Metric,
		arg.Count,
	)
	return err
}
