/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as SourcesIdRouteImport } from './routes/sources/$id'
import { Route as SettingsOrgRouteImport } from './routes/settings/org'
import { Route as SettingsMembersRouteImport } from './routes/settings/members'
import { Route as SettingsInvitesRouteImport } from './routes/settings/invites'
import { Route as SettingsAuditRouteImport } from './routes/settings/audit'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as OrgsNewRouteImport } from './routes/orgs/new'
import { Route as InvitesTokenRouteImport } from './routes/invites/$token'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as DestinationsIdRouteImport } from './routes/destinations/$id'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsInvitesRoute = SettingsInvitesRouteImport.update({
  id: '/settings/invites',
  path: '/settings/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/destinations/$id',
  path: '/destinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/invites': typeof SettingsInvitesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/org': typeof SettingsOrgRoute
  '/sources/$id': typeof SourcesIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/invites': typeof SettingsInvitesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/org': typeof SettingsOrgRoute
  '/sources/$id': typeof SourcesIdRoute
  '/destinations': typeof DestinationsIndexRoute
  '/events': typeof EventsIndexRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/orgs/new': typeof OrgsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/invites': typeof SettingsInvitesRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/org': typeof SettingsOrgRoute
  '/sources/$id': typeof SourcesIdRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/destinations/$id'
    | '/events/$id'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/invites'
    | '/settings/members'
    | '/settings/org'
    | '/sources/$id'
    | '/destinations/'
    | '/events/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/verify'
    | '/destinations/$id'
    | '/events/$id'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/invites'
    | '/settings/members'
    | '/settings/org'
    | '/sources/$id'
    | '/destinations'
    | '/events'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/verify'
    | '/destinations/$id'
    | '/events/$id'
    | '/invites/$token'
    | '/orgs/new'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/invites'
    | '/settings/members'
    | '/settings/org'
    | '/sources/$id'
    | '/destinations/'
    | '/events/'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  DestinationsIdRoute: typeof DestinationsIdRoute
  EventsIdRoute: typeof EventsIdRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
  OrgsNewRoute: typeof OrgsNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsInvitesRoute: typeof SettingsInvitesRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsOrgRoute: typeof SettingsOrgRoute
  SourcesIdRoute: typeof SourcesIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/invites': {
      id: '/settings/invites'
      path: '/settings/invites'
      fullPath: '/settings/invites'
      preLoaderRoute: typeof SettingsInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  DestinationsIdRoute: DestinationsIdRoute,
  EventsIdRoute: EventsIdRoute,
  InvitesTokenRoute: InvitesTokenRoute,
  OrgsNewRoute: OrgsNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsInvitesRoute: SettingsInvitesRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsOrgRoute: SettingsOrgRoute,
  SourcesIdRoute: SourcesIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
